### ISSUE TITLE
Framed Half Vertical Stairs

### ISSUE THREAD

**Issue by ASlipperySlope** [XFactHD/FramedBlocks#100]
I found it weird how the mod includes half stairs, but no half vertical stair. Is there a reason for this, or was this an oversight?

**Comment by XFactHD** [comment]
Just an oversight. No idea why I didn't think of that when I originally added the half stairs :D
Will be added for the next update.

**Comment by ASlipperySlope** [comment]
Was this not pushed out for 1.18.1?

**Comment by XFactHD** [comment]
You are correct. I would prefer to drop 1.18.1 support except for critical bug fixes because the user base seems to have moved on to 1.18.2 for the most part (at least according to the download counts for the last two releases for .1 and .2 - 81k vs. 2k and 27k vs. 1.2k).

In this specific case, back-porting this feature to .1 is trivial, so I would not be totally opposed to making an exception here.

**Comment by XFactHD** [comment]
You are in luck. I have to push an update to fix a crash and decided to include this feature there as well.

**Comment by LindaJuffermans** [comment]
Will this be pushed to 1.16.5 as well?

**Comment by XFactHD** [comment]
1.16.5 is still in active development, so it will also receive most changes and all features that are added in 1.18.2.
This feature was released for 1.16.5 with version 2.15.0

**Comment by LindaJuffermans** [comment]
Thank you! 💗
