### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by CuriousGamer2** [XFactHD/FramedBlocks#104]
Not really an issue more of a question. I see hat 90 issues have been closed regarding this mod, does that include the known issues about using Sodium too?

**Comment by XFactHD** [comment]
If you are referring to the known issues mentioned on the CurseForge page, then the answer is no, I can't fix those. As a short explanation:
- Block lighting: Sodium seems to modify the quad lighting heavily and may even override the extended quad lighting implementation provided by Forge (which has to be active for proper lighting, as mentioned on the CF page)
- Biome Blending: Sodium does the biome blending completely differently than vanilla Minecraft. When this issue was initially reported to me, they did a lot of block comparisons, which I can't fake to have them recognize a Framed Block as whatever colorable block I need
- Ghost block rendering: Sodium completely overwrites the method I need to insert a call into for the ghost block rendering, they basically delete all the code in that method and replace it with their own. There is nothing I can do about this, except either crash or disables the placement preview
- Face hiding: This may not be a fatal issue anymore as the involved code has been rewritten once in the 1.16 version and a second timd in the 1.18.2 version, though while it won't crash anymore I can't guarantee that it will work. The reason for the crash was very similar to the point above IIRC

**Comment by XFactHD** [comment]
I'll close this issue for now.
If you have any further questions, feel free to ask in this issue.
If you find any issues that are not mentioned on the CF page, then please open an issue with relevant details.
