### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by PestoPosta** [XFactHD/FramedBlocks#109]
I don't know how much of a pain in the neck it would be, but I would love to have the ability to combine frames other than slabs,
IE a stair + a slab edge, a slab + a frame slab corner, a vert stair + corner pillar, and so on.
I assume its doable since slabs can be joined, and it would move this mod up to god tier.

Cheers, thanks for your time.

**Comment by XFactHD** [comment]
This is unfortunately not going to happen. Every combination of two blocks is a dedicated block with very specific behavior. This cannot be generalised to work with arbitrary combinations of different shapes. Apart from that it's also out of scope for this mod as the intention is to provide mostly simple shapes. Which blocks get "double" variants is decided on a case-by-case basis when it makes sense. If you want to combine arbitrary shapes, then you are better off to use something like Chisels & Bits or other multipart mods.

Framed Slabs and Framed Panels are special cases, clicking a slab or panel with the respective item will replace the respective block with a different one that can handle two separate camos.

**Comment by PestoPosta** [comment]
Chisels & Bits is way more complex than I am looking for, and
I've played enough with it I love it and hate it at the same time.
Ultimately don't want anything to do with it.
Your mod is pretty much exactly what I am looking for,
I just wish I could combine eighths, quarters halves, & stairs.

At any rate, if I could encourage you to add the combo for stairs and quarter frames that would be a god send.

For my own curiosity, and under standing would you mind explaining in a bit more detail what the issue is. If not nbd. :)
Because as I said just looking at how the slabs work it seems like it should be the same thing, but I am no modder/coder.

Cheers thanks again for your time.

**Comment by XFactHD** [comment]
> At any rate, if I could encourage you to add the combo for stairs and quarter frames that would be a god send.

That's something I may look into, but at the moment it's unlikely to happen. This would also be limited to the full stairs, the half stairs will not get this treatment. The main thing I am not quite sure on for the horizontal stairs is whether the stairs should be able to have all shapes or just the straight shape. Including all shapes will make this really complex but only including straight may make it less useful.

> For my own curiosity, and under standing would you mind explaining in a bit more detail what the issue is.

All the double blocks (double slabs, double panels, double slopes and double corners) are completely separate blocks from their single variants and each of them is a discrete block with a lot of logic attached to it. This logic is mainly related to three things:
1. The detailed culling of faces between two Framed Blocks (i.e. if you place two slabs next to each other and put stained glass into both, then you will see that the two faces touching each other are culled only when both blocks have the same camo and not none)
2. Selecting which segment you hit when you click the block to apply or remove a camo.
3. Determining the orientation of the block when it's placed

This logic cannot be generalised to arbitrary combinations of shapes because the systems were not designed with that in mind and I don't plan on changing that. Multipart mods like Chisels & Bits take a completely different approach to this, which is why they can handle arbitrary combinations of shapes.
The Framed Slabs and Panels are a special case. While you need to place all other double blocks with a specific item, slabs and panels allow you to click an existing one with the respective item. In the end this leads to the same result though: a specialised block for the double variant. This is different from slabs in vanilla Minecraft where the double slabs are actually the same block as the single slabs but with a different state.

**Comment by PestoPosta** [comment]
Stairs:
Your kind enough to offer the mod up for free, so
no worries and no expectations :)

If it helps I've done a heck of a lot of building with the frames
and thus far the only instance of stairs I've needed were the vertical and horizontal.
I have not needed the corner stairs, but one does never know.

Personal edification:
Ok so if I grok, each block combo has to be its own block, so vert stairs left + the corner = its own block, vert stairs right etc.
Each block then needs to know how to behave, how to display textures etc.
Slabs are easy, because regardless of how they are facing, it is still essentially the same block.
Yeah that makes sense, thanks :)

I assume then chisels & bits's code is adaptive or predictive?
IE the code "thinks" how does this block shape work, and changes the hit box etc to behave accordingly.

PS:
If you'd like I'd be happy to shoot you a hand full of screenshots to show off what your mod is capable of. :)

**Comment by XFactHD** [comment]
> I assume then chisels & bits's code is adaptive or predictive

Chisels & Bits uses something like a 3 dimensional storage matrix that holds all the bits in the block. From that they can easily build the collision shape of the block. Their advantage is that they don't do per-bit occlusion AFAIK, i.e. a two glass bits next to each other will not hide the faces between them. They also don't have to take angled shapes into account when calculating the precise interaction point when placing or breaking a bit.

> If you'd like I'd be happy to shoot you a hand full of screenshots to show off what your mod is capable of. :)

Sure, I'd be more than happy to take a look. Please DM them to me on CurseForge.

**Comment by PestoPosta** [comment]
Chisels & Bits:
Groovy, thanks again. :)

Screen Shots:
As soon as I am able, I will.
