### ISSUE TITLE
How could I use World Edit with FramedBlocks ?

### ISSUE THREAD

**Issue by Axelouuu-dev** [XFactHD/FramedBlocks#112]
Hello !

I'd like to know if it possible to use //set command from WorldEdit to create framed block like double panel with two blocks into it ?

**Comment by XFactHD** [comment]
Unfortunately the documentation of WorldEdit seems to be nonexistent, so I have no way to check if they have any special handling for BlockEntity data.

For the `/setblock` command from vanilla Minecraft the command would look like this for a single block:
`/setblock -356 63 -260 framedblocks:framed_cube{camo_state:{Name:"minecraft:polished_granite"}, camo_stack:{Name:"minecraft:polished_granite"}}`
and like this for a double block:
`/setblock -356 63 -260 framedblocks:framed_double_panel{camo_state:{Name:"minecraft:polished_granite"}, camo_state_two:{Name:"minecraft:polished_diorite"}, camo_stack:{Name:"minecraft:polished_granite"}, camo_stack_two:{Name:"minecraft:polished_diorite"}}`.
The first one would place a Framed Cube with Polished Granite as the camo.
The second one would place a Framed Double Panel with Polished Granite and Polished Diorite as the camos.
If you need to rotate the block, then you also have to specify the `facing` property in square brackets between the block name and the first curly bracket.

Do note though that for a few blocks, especially the double blocks, you will run into issues with the character limit of the ingame chat. If you don't need the item to be dropped when you click the Framed Block with a Framed Hammer, then you can remove the `camo_stack` and `camo_stack_two` parts from the command. This should allow you to also place double blocks with most other blocks as camo.

**Comment by anniemuse69** [comment]
Regarding chat character limitation, you do not need to use "minecraft:" if not stated, it is assumed to be a vanilla block. The following command works and references EW vs NS double panels:

`/setblock 6 -53 39 framedblocks:framed_double_panel[facing=east]{camo_state:{Name:"polished_granite"}, camo_state_two:{Name:"polished_diorite"}, camo_stack:{Name:"polished_granite"}, camo_stack_two:{Name:"polished_diorite"}}` 

`//set granite` is a bulk command, and solution given does not work for multiple framed blocks. 
Kicks back the error:
`Invalid value for <pattern>
(Block name 'framedblocks:framed_cube{camo_state:{Name:"minecraft:polished_granite"}' was not recognized)
acceptable values are any pattern`

`Usage: //set <pattern>`

**Comment by anniemuse69** [comment]
The best workaround I found for the WorldEdit `//set` command is to:
1. Place a vanilla block / blocks and use the `\wand` to select them (`//pos1` and `//pos2` ).
2. Replace the blocks you selected with the desired framed block(s) manually.
_** it's annoying to skip step one, since the WorldEdit wand removes the camo from the framed block while setting `//pos1`. But unlike the framed hammer you can't replace the filled pattern / camo without re-creating the block, or using the framed hammer prior to replacing the camo.**_
3. `//copy` the framed block pattern to the clipboard
4. Then make a larger selection, where you wanted to `//set` the framed blocks, using  `//pos1` and `//pos2`
5. `//set #clipboard`
This would allow you to define a WorldEdit pattern with modded blocks and place the filled framed blocks in bulk to speed up build time.

You can also use the `\\rotate 90` or `\\rotate 180` command before step 5
Also `\\flip east` or `\\flip south` etc.
