### ISSUE TITLE
cant cycle through camo blocks on slopes.

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#118]
when i right click with the whrench on half slopes i cant get the grass texture to be on top as in nothing is actually happening.

**Comment by XFactHD** [comment]
The grass block doesn't have rotations. Rotating camos is only possible on blocks that actually have rotateable properties (i.e. logs which can be oriented on either of the three axis). Allowing rotation for blocks that cannot currently be rotated is not possible.

The slopes currently use the side of the block to make the sloped plane. I could look into adding the option to switch this to the top face, though that will likely introduce inconsistencies with certain blocks because I am running out of interaction types with the existing tool items.

**Comment by GreenForzeGaming** [comment]
What if the whrench became a "block rotator" and then add a "tile swaper"? The tile swaper could display the 6 sides of the block inside and let you choose what tile goes on the clicked surface. Also using shift could allow you to spin said texture.

________________________________

**Comment by XFactHD** [comment]
Rotating blocks as camo that cannot be rotated when they are themselves placed in the world and allowing you to select arbitrary faces of the camo for different faces is not possible due to how the data format of the faces works (this is a vanilla thing and there is nothing I can do to change this format).

Allowing you to switch between side face and top face for the sloped face is the only feasible option.

**Comment by GreenForzeGaming** [comment]
Interesting. Love the mod anyhow so thank you for your hard work!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
