### ISSUE TITLE
Blueprint Compat with Effortless Building

### ISSUE THREAD

**Issue by Tohricat** [XFactHD/FramedBlocks#119]
The mod, Effortless Building, allows users to place multiple blocks at once. Compatibility with the Blueprint from FramedBlocks would work wonders, but unfortunately it does not work when attempting to place multiple blocks (likely as the blueprint is not treated as a block). 

Apologies if this is the incorrect repo to post this in. Thanks for the wonderful mod!

**Comment by XFactHD** [comment]
The Blueprint is not a `BlockItem` because it has to replicate all of the placement logic from it anyway and also perform custom material consumption to actually apply the camo while placing, meaning it would be mostly incompatible with anything that would use it for a purpose similar to what Effortless Building is doing.

The support for the Blueprint would have to be done on their side, though I am not sure if that's something they would want to do since they would also need to handle the custom item consumption, especially because the implementation on my side could change at any time for various reasons.
