### ISSUE TITLE
Game crashes with CTM - Cannot get property as it does not exist in Block

### ISSUE THREAD

**Issue by Aviator737** [XFactHD/FramedBlocks#126]
Game crashes with CTM resoursepack.
[crash-2022-07-12_13.23.29-client.txt](https://gist.github.com/Aviator737/e7762ddd88cc0ebff85745138aec5136)

Steps:
1. Install [my ctm resourcepack](https://drive.google.com/file/d/1zBqRQ7QXKTIKUdZvKs6uQW8VG59WUsr9/view?usp=sharing)
2. Place "Framed Double Slope" and "Framed Inverted Double Slope Slab" next to each other
3. Put "Cracked Polished Blackstone Bricks" into "Framed Double Slope (upper part)"
![image](https://user-images.githubusercontent.com/6958547/178460514-41f23501-b791-48ad-8bf6-bdf7ea10a213.png)

I saw crashes with other framed blocks (even with phantom preview blocks), but it seems that this problem has a common solution

**Comment by XFactHD** [comment]
1. 1.16 is out of support
2. I cannot load that CTM pack as it requires OptiFine, which I can't load in a dev environment without significant effort
3. The crash in the crash report has nothing to do with the screenshot

If you can reproduce the supposed issue with the setup in the screenshot in 1.18 or 1.19, please open a new issue.

The crash in your crash report will be fixed in an upcoming update for 1.18 and 1.19
