### ISSUE TITLE
Distant Horizons compatibility 

### ISSUE THREAD

**Issue by Tohricat** [XFactHD/FramedBlocks#128]
Hello! 

First off, thank you for the Create contraption compatibility! I can't wait to start building with it. 

Is Distant Horizons compatibility something that would be considered? Currently, when viewing framed blocks from a distance (in a Distant Horizons fake chunk), it uses the color of the frame (brown) as opposed to the texture of the block inside it. This makes building with the mod hard when using it. I believe there is an API that could make this possible, but I haven't delved into the code properly yet.

**Comment by XFactHD** [comment]
Unfortunately there is nothing I can do about this. The underlying issue is basically the same as the one with Create contraptions: Distant Horizons would have to support the Forge `ModelData` system for this to work properly.
The fix on my side to make the blocks work properly on Create contraptions after they implemented support for the `ModelData` system may help with DH support as well, if they add `ModelData` support in the future.
