### ISSUE TITLE
[1.18] Crash with OptiFine Connected Textures

### ISSUE THREAD

**Issue by BloCamLimb** [XFactHD/FramedBlocks#130]
Description: If you put two `Framed Inverted Double Slope Panel` side by side, fill them with Sandstones (or other blocks with connected textures) and enable OptiFine Connected Textures, it will crash the game and show `Cannot get property BooleanProperty`. This is most similar to https://github.com/XFactHD/FramedBlocks/issues/126

Crash report: https://paste.mozilla.org/WduAtKpA

Mod version: 5.2.0, Forge: 1.18.2-40.1.52, OptiFine HD U H7

Note that OptiFine is not compatible with Forge 40.1.58 or above in singleplayer world, so I use the old version of both Forge and FramedBlocks. I don't really know if Forge 40.1.68 is a mandatory requirement of FramedBlocks 5.5.0, could you also make backward compatibility if possible?

I haven't seen any changelogs about this issue in the new 5.3.0~5.5.0 version, so I assume this issue can be reproduced in 5.5.0 as well.

**Comment by XFactHD** [comment]
Forge 40.1.68 is a mandatory requirement of FramedBlocks 5.5.0 because I need the features included in that version.

I have a fix for the crash, however it won't be available on any version with a Forge 1.18 version requirement that is compatible with OptiFine. I simply cannot care about OptiFine dropping support for an MC version while only supporting a (sometimes massively) outdated Forge version.
