### ISSUE TITLE
[Feature Suggestion]: Full Bar Blocks, Slabs, Trapdoors?

### ISSUE THREAD

**Issue by NoMoreStars** [XFactHD/FramedBlocks#139]
### Describe the feature

When whitelisted via a datapack to be used on frame blocks, iron bars and modded bar types display only in the neutral unconnected position (see attached image). I was going to make a feature suggestion suggesting that framed blocks use full textures for every side of the block, but due to the nature of iron bars I imagine that this may be outside the scope of the mod. Instead I propose that you add full framed bar blocks as well as potentially trapdoors.

![2022-07-26_17 24 13](https://user-images.githubusercontent.com/38673759/181123376-143f00e8-f925-41a3-b56e-a83abd34de79.png)

**Comment by XFactHD** [comment]
Getting the full textures from blocks that are not normal 6 sided full cubes is completely impossible since I would have to guess how the texture coordinates need to be expanded to get the full texture.

Adding actual blocks to use as camo is outside the scope of this mod, that's much better fit for a separate mod that just adds building materials and/or decoration blocks. I only provide the building blocks.
