### ISSUE TITLE
[Feature]: Improved Grass Stair Model

### ISSUE THREAD

**Issue by Charismara** [XFactHD/FramedBlocks#141]
### Describe the feature

Adding the "grassy" top edges to the bottom part of the model
![image](https://user-images.githubusercontent.com/14293974/181340720-dba9dee8-b3e3-4e5b-a70c-585f3d5917bf.png)

**Comment by XFactHD** [comment]
I like the idea, though I'm not sure how viable it is.
I'll take a look but absolutely no promises.

**Comment by XFactHD** [comment]
I have looked into this some more. While it is definitely possible, I have decided against it because the stairs block is already extremely complex in terms of the states it has (the stairs block has 648 different states it can be in due to the shapes, top/bottom half, the orientation, waterlogging and some other metadata needed to make my custom stuff work).

I am also not sure if the usefulness of this would outwheigh the issue of blowing up the state count even further due to the very limited amount of blocks this would be useful for. A mod purpose-built for a use-case like this would most likely serve you better: https://www.curseforge.com/minecraft/mc-mods/grass-slabs-carpets-stairs.
