### ISSUE TITLE
[Bug]: 1.19.1 version crashes the server on startup

### ISSUE THREAD

**Issue by SirEndii** [XFactHD/FramedBlocks#146]
### Minecraft version

1.19

### Forge version

42.0.1

### FramedBlocks version

6.2.0

### Describe the bug

When trying to start the server, the server crashes - nothing more

### How to reproduce the bug

Upload the mod on your server - start the server - poof
Does work on clients wonderful

### Expected behavior

No crashy 

### Additional details

Wonderful mod <3

### Crash log

https://gist.github.com/Seniorendi/268aa52692f42167d0f7b5b0edb47f4c

**Comment by XFactHD** [comment]
This is a known issue in Forge, see https://github.com/MinecraftForge/MinecraftForge/pull/8931 for the upcoming fix.

For context, FramedBlocks for 1.19(.1) includes a library that is used to efficiently cache the generated models and the system that is supposed to load that library has a bug that causes this to fail on dedicated servers.

I'll keep this issue open until this is fixed on Forge's side.

---

> Wonderful mod <3

Thank you, much appreciated 😃

**Comment by WildLONLON** [comment]
Sorry if i did wrong, i'm absolutely not used to GitHub, this is the first time that i used it !

Thanks for that, so i just have to wait for an Forge's Update ? Am i right ?

Indeed, your MOD is fantastic, I used it to create a surprise map for a Discord, that's why I must absolutely make it run on Server, otherwise the map will have been made for nothing !
(Especially since I used a lot of FramedBlocks features !)

**Comment by XFactHD** [comment]
> Thanks for that, so i just have to wait for an Forge's Update

Correct. I'll add the Forge version in here when it's fixed.

---

> Indeed, your MOD is fantastic

Thank you 😄

**Comment by XFactHD** [comment]
The fix is merged and available in Forge 1.19.1-42.0.2
