### ISSUE TITLE
[Feature]: Vertical Stairs Corner

### ISSUE THREAD

**Issue by Charismara** [XFactHD/FramedBlocks#149]
### Describe the feature

Basically like the default Stairs corners but vertically.

Example usage:
![2022-08-05_10 39 20](https://user-images.githubusercontent.com/14293974/183038480-b3481964-bf1a-48f1-baa7-3822fb3a1b0e.png)

**Comment by XFactHD** [comment]
Adding this is a huge pain in the backside and unfortunately not possible at the moment because it can break existing builds using this block.
I will keep it in mind for the MC 1.20 update though, since that allows me to make changes that break worlds.

However, there is a way to achieve this effect in the current version with the use of state-locking:

1. Replace the bottom vertical stairs with normal stairs
2. Place an additional stairs block in front of that to achieve the shape you want
3. Click the corner stairs with the Framed Key to lock its state
4. Remove the additional stairs block
5. The corner stairs block will keep the corner shape

**Comment by XFactHD** [comment]
I've decided against this for the time being as this can be achieved with pure vanilla behaviour (doesn't even require the locking mechanic mentioned above) by placing the stairs block that should form the corner at 90 degrees (counterclockwise in your example) to the straight one.
