### ISSUE TITLE
[Bug]: ConcurrentModificationException in FramedFlowerPotModel.getOrCreatePotModel

### ISSUE THREAD

**Issue by zbx1425** [XFactHD/FramedBlocks#152]
### Minecraft version

1.18

### Forge version

40.1.59

### FramedBlocks version

5.2.0

### Describe the bug

`ConcurrentModificationException` on `CACHE_BY_PLANT` since HashMap isn't thread safe.
The 1.19 branch employs caffeine.cache, while the 1.18 branch does not. May I ask when it will come to 1.18?

### How to reproduce the bug

Place multiple framed flower pots in different chunks, and there is a chance that this might occur.

### Expected behavior

The game should not crash.

### Crash log

https://gist.github.com/zbx1425/99e4acde180e7479265c16563e05847b

**Comment by XFactHD** [comment]
Of course there had to be *one* spot where I forget to safeguard against concurrent modification...

As for the fix:
Caffeine will not come to 1.18 just for this. The reason it's included in 1.19 is that I am using it as the main cache for the generated models. Using it for that purpose in 1.18 is not viable and including it just for the flower pot is not an option due to the size of the library.
I'll have to check what the most performant way to fix this is.

**Comment by XFactHD** [comment]
Simple synchronization turned out to be the best solution in this case.
