### ISSUE TITLE
[Feature]: cylinder/arch frame blocks +quality of life (qol) fixes/improvements

### ISSUE THREAD

**Issue by weshuiz** [XFactHD/FramedBlocks#157]
### Describe the feature

**cylinder frame block**
for the cylinder there is not much to explain other then the option to be horizontal/vertical
having pillar like blocks seems like it always was in the mod but strange;y is not

**arch frame block**
for the arch frame blocks having the option to make it arch in multiple directions should be great
any combination of Nort/East/South/West direction should be posseble
this would allow for double arches as well

**individual texture sides**
what i meant by this is that frame blocks should allow for each side of a frame to be textured diffrently, finding some situations where i wished the top of a frame could have a diffrent texture then the sides
i'm aware there are floor and wall panels but there is no option for certain blocks such as slopes
blocks like those are doomed to have 1 texture all around and no way to cover the other sides
i suggest most block/if not all should allow to place a texture per side rather then as a whole

**dioagnal decoration blocks**
another thing that seems somewhat of a problem is the lack of dioagonal placements, and i'm meaninly talking about things such as walls/panes/bars those things can not be placed dioagonal unfortunately, and would love to see this chaned in the near feature

**question/tweak**
another thing is that floor/wall panels still remain to be 1px thick rather then flat, this is a question and a hopefully chance as well

**more double half blocks**
the half slab frame block can just like a regular slab be staqcked and form a full block, yet it allows to host 2 difrent half slab textures on it this is amazing as double slabs is something that is been talked about for years in the MC community
but what is less amazing is that vertical slabs/half stairs do not support this oddly enough
if this could be fixed/added it would be amazing

**Comment by XFactHD** [comment]
**Cylinder and Arch**:
Rounded shapes will not happen, they are not possible with the way this whole mod works.
An arch with the "round" section being built from three or four quads at different angles is something I could look into but that would be a candidate for the architecture-focused addon I am working on. I don't think this would be a particularly useful approach for a cylindrical pillar though.

**Individual textures per side**:
This is not going to happen. It would blow up the amount of data contained in these blocks, making them far more likely to cause issues. The data being heavily limited is the reason why you can build gigantic things with these blocks and not run into major issues.

**Diagonal blocks**:
The diagonal fences are a mod support implementation related to the [Diagonal Fences](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences) mod. The author is planning to support walls and panes at some point and when it happens, I will add support for it. Please don't harass them about it though, it's ready when it's ready.

**Floor Baord and Wall Panel thickness**:
That is intentional to avoid confusion about which actual block space the block is in. If you really need a completely flat block, then use a Framed Collapsible Block and hammer it flat. The block can be copied with a Framed Blueprint, so only need to do it once as long as the orientation is the same.

**More double blocks**:
The Framed Panel ("vertical slabs") can be combined into a double variant in exactly the same way as slabs can be combined into double slabs. This is even indicated by the ghost block placement preview when holding a Framed Panel.
Some more double blocks are planned, mostly related to other planned blocks, but double half stairs are not currently on that list. I will think about adding them though.

**Comment by weshuiz** [comment]
thank you kindly for your friendly response
and listening to my feedback

i can understand there would be some limitations, those where just suggestions anyways
this mod has huge potential to be even greater than it already is
also thank for the tips i was not aware of some features the mod has

and reguarding the diagnal fances, i will take a look, dispite it not being finished
i shall wait untill it gets finished, i do not support or condone Harassment
