### ISSUE TITLE
[Bug]: flat collapsible block layer issue

### ISSUE THREAD

**Issue by weshuiz** [XFactHD/FramedBlocks#161]
### Minecraft version

1.19

### Forge version

43.1.1

### FramedBlocks version

6.3.0

### Describe the bug

A flattened collapsible block will cause layer issues or Z-fighting when placed on certain blocks/directions

### How to reproduce the bug

1. place any kind of **solid block**
2. place a framed collapsible block next to said block **facing:** North, West or Down
3. hammer it flat
4. (optional) apply a texture

### Expected behavior

the texture of the collapsible block should layer over the block it is placed on

### Additional details

the solid block's texture will overlay the flat collapsible
and some blocks will cause Z-fighting however not every block does this such as a coal block

Non solid blocks such as glass seems uneffected by this bug
imgur preview link: [here](https://imgur.com/a/iuuLgdO)

**Comment by XFactHD** [comment]
This is a really annoying issue. If I fix the z-fighting by keeping the thickness slightly above 0, then the block will look weird when placed without another block behind it (i.e. as a zero-width wall) due to the minimum thickness needed to prevent the z-fighting from more than 1 or 2 blocks away.

I'll keep the issue open for now, no promises on when this will be fixed.

**Comment by XFactHD** [comment]
I've looked into this a bit more and found that it's not as bad as I expected in relation to having nothing behind the collapsible block.
The fix I am going to deploy is not magic though and will only fix the z-fighting up to a distance of about 20 blocks when using an FOV of 85. Fixing this completely would require giving the collapsible block a minimum thickness that is obvious from a fairly high distance, which I really want to avoid.
