### ISSUE TITLE
[Feature]: Rounded corner frames

### ISSUE THREAD

**Issue by tizu69** [XFactHD/FramedBlocks#162]
### Describe the feature

As I recently played around with the new Trains in the Create mod ( https://www.curseforge.com/minecraft/mc-mods/create ), I'd like to see rounded frame blocks (like Create's train tracks). You would place them by clicking once to set Pos1, then click somewhere else to set Pos2. I'd like to see them get smoothed just like when placing Create Tracks while holding Ctrl. Since Create is open source, I suppose someone may be able to simply copy some code for the basics, I don't know tho. Thanks!

**Comment by XFactHD** [comment]
I love the idea, but this is unfortunately neither possible nor viable at the moment.
This may be possible in the future as an addon between Create and FramedBlocks but don't get your hopes up.

---

The work done by the Create devs is amazing. They have some extremely clever people on their team.
What they are doing is mathematically fairly complex and something I simply don't have the time to get into at the moment (if you are interested, take a look at this video about Bézier curves https://www.youtube.com/watch?v=aVwxzDHniEw, it's a fascinating topic).

Highly dynamic shapes like that are also not really possible with the current systems (the collapsible block is already pushing the boundaries), mainly due to how the quads (faces of the blocks) are generated, cached and rendered, which would likely lead to high memory consumption and potentially rendering lag in areas with a lot of blocks. There is a reason why Create uses their homebrew rendering system aka Flywheel.
