### ISSUE TITLE
[Bug]: Texture missing when tilling farmland

### ISSUE THREAD

**Issue by Hiconel** [XFactHD/FramedBlocks#163]
### Minecraft version

1.18

### Forge version

40.1.71

### FramedBlocks version

5.6.0

### Describe the bug

The backside texture is missing. Big is only minor because it this disaapears after you rejoin the world. I only tested it with vertical stairs.

![image](https://user-images.githubusercontent.com/1748758/186994255-e80c172c-7703-4ef7-955a-2c3fea577037.png)

### How to reproduce the bug

1. Place the vertical stairs next to grass, dirt, etc.
2. Apply a block texture to the framed block
3. Then till the soil with a hoe to create farmland
4. Stand on the farmland and look the vertical stairs to see the missing texture

![image](https://user-images.githubusercontent.com/1748758/186995063-d78e805d-1fdc-4a37-aa2d-f414270a106e.png)

### Expected behavior

On the back there should be the same texture as the front.

**Comment by XFactHD** [comment]
This is going to be an interesting one to fix. It's low priority though since the issue is not persistent, leaving the area or reloading the world fixes it.

If it bothers you, there is a keybind to update the culling state of framed blocks called "Update culling" (for reference, culling is the process of hiding things that aren't visible anyway, like the back side of that vertical stairs block while it is covered by the dirt block). Looking at the affected block and pressing that key will fix the issue immediately.

**Comment by Hiconel** [comment]
Yeah, it's definitely not a big issue, just thought I'd report it since I noticed it. Also, thanks for the keybind tip! 😊

**Comment by XFactHD** [comment]
I appreciate every bug report no matter the severity, especially when done properly like this one 👍.

**Comment by XFactHD** [comment]
Found a surprisingly simple way to fix this, which will be included in the next update.
