### ISSUE TITLE
[Feature]:  Block pieces.

### ISSUE THREAD

**Issue by Ayria** [XFactHD/FramedBlocks#166]
### Describe the feature

Smaller block  that can be stacked to create a whole block that each corner can have it's own texture. Similar to a half slab, but 4 pieces instead of two.(Actually one crafted piece that can be placed in all for corners of a block)

Hope this is actually something that can happen.

If this is something thats already in and I haven't figured it out yet.. just omg.

**Comment by XFactHD** [comment]
The single-camo variant of what you are asking for is already a thing in the form of the Framed Slab Corner.
Multi-camo variants of that will not happen though. More than two camos on a single block are simply not viable due to the way this mod works. For applications where you need a higher amount of different textures within a single block, you are better off using something like Chisels & Bits which is specifically made with that in mind.

**Comment by Ayria** [comment]
What about being able to have the Framed Slab Edge fill in the missing bit on a stair? Thats only two camos. It would mean interesting windows shapes. Again if this is already possible in a way I haven't figured out.. -.- I swear I'm not being dumb on purpose.
![2022-09-03_20 56 45](https://user-images.githubusercontent.com/9374642/188293863-d733e14d-1cff-413a-8d2c-0c2e9e6d6dc5.png)

**Comment by XFactHD** [comment]
That feature exists since versions 6.1.0 for 1.19 and 5.4.0 for 1.18, which have been released on the 27th of June, in the form of the Framed Double Stairs and Framed Vertical Double Stairs.

**Comment by Ayria** [comment]
Thank you for being so patient with me. You're doing such great work!

**Comment by XFactHD** [comment]
Don't worry about it, happens to everyone ;)
I appreciate the suggestions nonetheless, keep them coming.
