### ISSUE TITLE
[Bug]: Fails to start after removing Create mod

### ISSUE THREAD

**Issue by AngleWyrm10** [XFactHD/FramedBlocks#170]
### Minecraft version

1.18

### Forge version

40.1.79

### FramedBlocks version

5.7.0

### Describe the bug

Error screen at game start, declaring FramedBlocks needs create
CurseForge page doesn't list any such dependency

### How to reproduce the bug

Add Create to mod pack and start a game. Exit
Remove Create from mod pack
Attempt to start a new game

### Expected behavior

No dependency listed, expected no error

### Additional details

Additionally tried removing the files under /config that were for Create and for FramedBlocks

**Comment by XFactHD** [comment]
FramedBlocks has no mandatory dependency on Create. Without the crash report there is nothing I can do about this. Please provide the crashreport on a paste site as requested in the issue template.

**Comment by XFactHD** [comment]
Turns out I made a copy-paste error on the mod ID in the check that would have prevented the calls into Create and it checked against Flywheel (which you didn't disable) instead of Create.
I will add that the error screen you got does not mention anything about a dependency, it mentions an exception that occurred because the safeguard that should have made Create an optional "dependency" failed. This would also have been visible in the crash log that is requested in the issue template.

Since this is an extremely minor issue, I will include the fix for it in the next big update.
