### ISSUE TITLE
not much of an issue but more of a stand alone block. a croner connection block for vertical and horizontal stairs would be nice

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#171]
### Describe the feature

![2022-09-24_14 56 34](https://user-images.githubusercontent.com/62345403/192099286-973b7552-44f2-4b38-b497-46bef0b890c6.png)

**Comment by GreenForzeGaming** [comment]
also a stair piece that has a half block with a half slope on top for diagonal stairs would be cool aswell

**Comment by XFactHD** [comment]
Your first suggestion is basically just a normal stairs block with the inner corner shape. In 1.20 the vertical stairs will be able to create that shape as well but adding this now would break existing builds with this block. This wouldn't help you though since you have no neighboring blocks that would force the vertical stairs into that shape.
To achieve the effect you want, you can use the "state lock" feature: place a second stairs block on the right side of the one in the screenshot so the first one switches to the inner corner shape, right click the first stairs block with the Framed Key, break the second stairs block and the first one will keep its shape.

For your second suggestion: not sure what kind of shape you are going for, can you elaborate on that (preferably with pictures)?

**Comment by GreenForzeGaming** [comment]
![image](https://user-images.githubusercontent.com/62345403/192497981-ddc8567f-ba32-496e-a400-e3e2d74881bc.png)

**Comment by GreenForzeGaming** [comment]
i love how open for suggestions you are, i beleve we had a discussion way back about 1.16 about grass being the top block and a tool that would be used to make that happen to slopes so the grass texture would be used on the top XD. also a slab tall triangle like that would be cool too honestly in all X Y Z ang
![image](https://user-images.githubusercontent.com/62345403/192499064-cc93e561-f0c3-42bd-9ed8-0b572c2a83e2.png)
els, also the i beleve 22 degree angle slab and block has X and Y but not Z

**Comment by GreenForzeGaming** [comment]
i made the picture show what angle ive wanted but dosnt exsist XD

**Comment by XFactHD** [comment]
> ![image](https://user-images.githubusercontent.com/62345403/192497981-ddc8567f-ba32-496e-a400-e3e2d74881bc.png)

Hmm, that's an interesting concept. I have some ideas on how to expand on that.
Also, that's one of the cleanest and most understandable illustrations I have ever gotten for a concept.

&nbsp;

> a tool that would be used to make that happen to slopes so the grass texture would be used on the top

That's still on my todo list. I may get to that after the next big update.

&nbsp;

> els, also the i beleve 22 degree angle slab and block has X and Y but not Z

The placement behaviours of the Framed Slope Slab and Framed Slope Panel are fairly complex.

- Framed Slope Slab:
  - Uses the block face you are looking at when placing as its direction unless you are looking at a top or bottom face, in which case it uses the player's look direction.
  - If you are looking at the top face of another block, the slope slab will be placed in the lower half of the block, if you are looking at the bottom face of another block, the slope slab will be placed in the upper half of the block and if you are looking at the side of another block, the half it's placed in is dependent on wether you are looking at the top or bottom half of that side (similar to how normal slabs work). 
  - If you are holding the crouch key while placing, the slope will face downwards, otherwise it will face upwards
- Framed Slope Panel:
  - Always uses the players look direction to determine the placement direction
  - When you are looking at the side of the block the slope panel's flat face will be placed against, then the rotation of the slope will be determined by the triangle section you are looking at (the triangle sections are formed by putting two imaginary crossing diagonal lines on the block face). When you are looking at the side of a block that is more than 45 degrees off from you look direction or you are looking at a top or bottom face, then the half width side (the "panel" side) will be pointing towards that block
  - When you are looking at the side of a block that is more than 45 degrees off from you look direction or you are looking at a top or bottom face and you are looking at the horizontal half that is closer to you, then the slope panel will be placed in the "front" half of the block space, otherwise it will be placed in the "back" half of the block space

These are the possible rotations of the Framed Slope Panel (if they were placed in the "front half" of the block space, then there would be a half block wide air gap betweent the glass blocks and the Framed Slope Panels):
![2022-09-27_18 50 06](https://user-images.githubusercontent.com/11262040/192589351-50657e42-c6c8-4686-ab78-ce9711fc9f3e.png)

I hope this clears up the confusion a bit. I would suggest playing around with the specific position of the cursor on the neighboring block and your rotation in relation to the block you are looking at. The ghost block preview rendering will show you what's possible.
At some point I want to make a wiki in the repository that goes into detail on the special placement behaviours of the blocks.

**Comment by GreenForzeGaming** [comment]
thx so much for the quick and absolute messeges. i have never had this good of a convo or help by any modder ever. thank you
