### ISSUE TITLE
[Feature]: other hidden blocks for trolling and estetics

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#175]
### Describe the feature

a bed would be cool, just the bottom wooden layer
tnt couse trolling is fun.
item frames could be really cool. like you place the framed frame <-- (best name ever) onto the wall, then apply an item in to it before it can be used as a normal frame. coolest would be for it to have a single surface instead of a wooden frame and a leather inside. lets say a sideways wooden pressure plate. this would allow us to make plates, cutting boards. signs for shops you name it.

**Comment by XFactHD** [comment]
- A Framed Bed is planned but it will be part of a furniture oriented addon, see #125 for the existing request.
- Item frames are a nice idea, I'll add those to the todo list

**Comment by XFactHD** [comment]
I've added the item frames, they don't have 100% feature parity with the vanilla frames though:

- Clocks don't work, they always point to noon
- Compass doesn't work, it always points north
- Putting a map into the frame won't add a marker at the frame's position onto the map

This is due to those features relying on a detail that I cannot replicate while also adding the FramedBlocks features onto the frames.

**Comment by GreenForzeGaming** [comment]
That is still really cool! Will this be 1.18? Also is there any work done on those diagonal half slabs? Id love to jse those xD

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XFactHD** [comment]
Yes, the item frames will be backported to 1.18 as well. I always add new blocks and features to both actively supported versions unless it would break existing worlds in any way.

The diagonal slabs are on the TODO list but no ETA when they'll be done.

**Comment by GreenForzeGaming** [comment]
Poggers!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
