### ISSUE TITLE
[Question]: Missing certain blocks (for example Framed Double Slab)

### ISSUE THREAD

**Issue by Tulu473** [XFactHD/FramedBlocks#179]
### Question

are certain blocks version specific? I'm on 1.18.2, using newest version (5.7.1) but seem to be missing certain blocks, like the Framed Double Slab, 
![javaw_eM1GvTn48e](https://user-images.githubusercontent.com/39826439/193681186-4ed22002-05a4-4496-a51c-6adf1ea3f990.png)

Also unrelated, is there a way to have a slab corners made from different materials? for example in this picture I need a Wood Framed Panel and then a Concrete Framed Slab Corner, are such combinations possible by the user or would that be something you would need to add yourself if needed?
![javaw_937WSXiVRH](https://user-images.githubusercontent.com/39826439/193682194-acec993f-b773-4beb-92e1-2388ca9ef021.png)

**Comment by Tulu473** [comment]
Ok I feel very dumb, you just stack two slabs to make a "double slab" and then assign a different material to each, theres no block with that name... I thought i was missing something.

**Comment by XFactHD** [comment]
Don't worry about it. The documentation is severely lacking when it comes to this kind of stuff. I want to get that up to standards but haven't fully decided yet on how to document it.
Most blocks are somewhat version-specific in the sense that they are not added to versions that aren't supported anymore at the time where the block is added. The 1.16 version for example is missing almost all blocks that were added after the first 1.19 version was released.

&nbsp;

> Also unrelated, is there a way to have a slab corners made from different materials? for example in this picture I need a Wood Framed Panel and then a Concrete Framed Slab Corner, are such combinations possible by the user or would that be something you would need to add yourself if needed?

This would need to be added to the mod by me. However, due to how the double blocks (like the double slabs) work in terms of data storage and how they interact with surrounding blocks, it is not feasible for me to allow arbitrary combinations of shapes in one block space.
If you need this kind of arbitrary combination of shapes, then you are better off using somthing like Chisels & Bits for these cases. It allows you to build these shapes while sacrificing a bit of the simplicity of just placing a block down and being done.

**Comment by Tulu473** [comment]
Thank you for the response and the support :) your mod is awesome by the way, the freedom it gives to create things is great. I will look into Chisels & Bits for the very few cases some blocks combinations.

**Comment by XFactHD** [comment]
Thank you, much appreciated. Happy that you like it :)
