### ISSUE TITLE
[Bug]: Liquid camo disappears on relog

### ISSUE THREAD

**Issue by Toastr125** [XFactHD/FramedBlocks#182]
### Minecraft version

1.19

### Forge version

43.1.25

### FramedBlocks version

6.4.0

### Describe the bug

When a bucket is used to add a fluid camo to a block, it reverts to having no camo when closing and reopening the world

### How to reproduce the bug

1. Place any framed block (I used framed floor boards and framed cubes for testing)
2. Use a bucket with a fluid in it on the block (I used water for testing)
3. Exit the world
4. Re-enter the world

### Expected behavior

The framed block would keep its fluid camo

### Additional details

This works on servers too, which is particularly strange. I was able to water camo a floor board and pick it back up in a bucket normally, but when I water camo'd a floor board and then disconnected and reconnected, it reverted to no camo and I wasn't able to pick it back up with a bucket. The server didn't even restart, I just disconnected and reconnected. I haven't gotten a chance to test it with another player present yet, so I don't know what they would see or whether it would even happen with them there.

**Comment by XFactHD** [comment]
Oops, that's what I get for forgetting to test saving and loading.
Turns out I didn't adjust the main safeguard against invalid camos, which therefore considered fluids invalid and deleted them when loading from disk.

The reason you could also reproduce this on a server by just disconnecting and reconnecting is that the server will unload and save the chunks you were in when no other player is close and when you reconnect they are loaded from disk again, which ran into the problematic check.
If you had another player close to you, everything would look correct for them until you both leave the area or the server and come back, were you would then both find the result you encountered on your own.

I'll try to get a new build with this fix out within the next 48 hours.

**Comment by XFactHD** [comment]
New version with the fix for this is available on CurseForge.
