### ISSUE TITLE
[Bug]: Server Config Not There

### ISSUE THREAD

**Issue by TheGetGoodGit2211** [XFactHD/FramedBlocks#190]
### Minecraft version

1.18

### Forge version

40.1.80

### FramedBlocks version

5.8.0

### Describe the bug

For some reason when I try to find the server config so i can turn on intangibility it just isn't there. I've checked.

### How to reproduce the bug

Just load up a profile and try to find the config after game launch. it won't work. I mean I made a world and everything.

### Expected behavior

A server config with relevant configuration options should appear.

**Comment by XFactHD** [comment]
Where exactly did you search for the server configs?

**Comment by TheGetGoodGit2211** [comment]
@XFactHD In the config folder of the instance

**Comment by TheGetGoodGit2211** [comment]
@XFactHD sorry dude i just realised it's in the serverconfig folder of the save. I do still wish there was a universal config for all worlds though that overrides the world specific config.

**Comment by XFactHD** [comment]
You can provide default server configs that are copied to new worlds by copying the server config file from the serverconfigs folder of a world to the defaultconfigs folder of the instance. The only downside is that modifying a config in that folder will not influence existing worlds.

Providing the options from the server config in the common config is not an option however because the settings of the server config must be synchronized between server and client, which is exactly what the server config does.

I'll close the issue as resolved. If you have any further questions, feel free to ask anyway.

**Comment by TheGetGoodGit2211** [comment]
@XFactHD Can I just ask are you ok to divulge any details for any future additions to me? I really love this mod way more than other similar mods cause it just adds so much damn content it's unbelievable.

**Comment by XFactHD** [comment]
All currently planned content is visible as issues on this repository, except for one feature that was suggested via a CurseForge DM, which is more fancy rails where you can apply a camo to the bars the rail stock rests on.
I'd recommend reading through the open issues tagged with `enhancement` for more details.
