### ISSUE TITLE
[Feature]: Fabric1.18.2

### ISSUE THREAD

**Issue by 5ur3z** [XFactHD/FramedBlocks#195]
### Describe the feature

Is there any plan for move to Fabric?

**Comment by XFactHD** [comment]
Moving to Fabric is completely out of question, that's not going to happen. Porting to Fabric would be possible but I currently have neither the time nor the interest to do it. See previous responses to this question for more detail: https://github.com/XFactHD/FramedBlocks/issues?q=label%3Afabric

**Comment by SrRapero720** [comment]
just and extra opinion:
fabric not give extras things over forge. so is useless increase the work porting into a other modloader with other problems.

**Comment by XFactHD** [comment]
Your comment adds nothing productive to this conversation. There are plenty of reasons why someone might want to use one modloader instead of the other, both as a developer or as a player.
If you have opinions why either one is worse than the other, then it's best if you keep them to yourself. Anything else just tends to start a useless flamewar.
