### ISSUE TITLE
[Feature]: a config option to specify how many framed torches you 

### ISSUE THREAD

**Issue by TheeMrCheeky** [XFactHD/FramedBlocks#197]
### Describe the feature

 a config option to specify how many framed torches you

**Comment by XFactHD** [comment]
Can you elaborate? Your message is cut off, so I have no idea what you are requesting.

**Comment by TheeMrCheeky** [comment]
oh my bad, :,D Like when you craft framed torches.. Maybe a way to change how much material & how many the out come is. like 1 framed blocks and 1 pieces of coal I could set to giving me like 2 torches instead of 4, or 2 framed blocks and 2 pieces of coal I could set to giving me like 8 torches instead of 4..

**Comment by XFactHD** [comment]
The recipes are inherently configurable since they are defined in datapacks. Apart from that, adding config options that control the item counts of these recipes would require re-inventing the wheel.

To change the recipe of the Framed Torch to your liking, you need to override this recipe file with a datapack: https://github.com/XFactHD/FramedBlocks/blob/1.19.x/src/generated/resources/data/framedblocks/recipes/framed_torch.json. If you are not comfortable with making a datapack by hand, then I may suggest using RecipeBuilder (see the CurseForge page for more details) which I made to allow generating datapacks with an interactive UI.
