### ISSUE TITLE
How did I do this? 

### ISSUE THREAD

**Issue by Ivybug** [XFactHD/FramedBlocks#201]
### Question

I was using framed collapsible block and made this: 
![yes brick](https://user-images.githubusercontent.com/31493821/200143125-22502ea3-66ed-4ea7-bdfd-e11fd351c144.jpg)
The brick slopes evenly from on diagonal to the other, making a smooth triangle sloping down. 

But when I tried to do it again on another collapsible block, the top kept caving in, making a "v" shape on top, instead of a smooth angle down. 

![No brick](https://user-images.githubusercontent.com/31493821/200143182-79bc6b03-67c9-4de5-970a-a1278b4159a9.jpg)

So my question is, how do I recreate the first block? As far as I can tell I am doing the same things, but I can't stop the top from making that v shape. 

Can you help?

**Comment by XFactHD** [comment]
What you are seeing there is a fairly simple issue: Minecraft internally represents the faces of a block as quads (2D shape with 4 corners) but when your graphics card actually draws these faces on the screen, the quads are converted to triangles because modern GPUs can only draw triangles (triangles are the most versatile shape to make arbitrary 3D shapes out of).
If you change the corner positions of the collapsible block in a way where the four corners are not on a flat plane (which is what is happening in this example), a diagonal edge is visible due to the quads being rendered as two triangles. This diagonal edge always points in the same direction dependening on the side (i.e. the top side always has this edge between the north-west and south-east corner), which is why you cannot reproduce the shape from the first block on the second one.

Unfortunately there is nothing I can do about this, it's simply how computer graphics work.
However, there is a new block coming up that would fit perfectly for your use-case: https://github.com/XFactHD/FramedBlocks/issues/171#issuecomment-1259279333, so you may want to keep an eye on that issue.
