### ISSUE TITLE
[Bug]: framed fancy rail crash

### ISSUE THREAD

**Issue by Sunekaer** [XFactHD/FramedBlocks#208]
### Minecraft version

1.18

### Forge version

40.184

### FramedBlocks version

5.9.1

### Describe the bug

Whenever framed slopes are right-clicked on a server it crashes the client.

### How to reproduce the bug

1.Place Framed Slope
2.Right Click Framed Slope

### Expected behavior

Not crashing the client

### Crash log

https://github.com/FTBTeam/FTB-Modpack-Issues/files/9984657/crash-2022-11-10_20.56.40-client.txt

**Comment by XFactHD** [comment]
I can't reproduce this in a dev environment, so it's very likely a mod interaction.
This specific kind of crash is often caused by another error earlier on, so I'd need the debug log (no idea whether the FTB launcher also disables this for inexplicable reasons like CurseForge does) from when this crash occured to find the actual error.

**Comment by Sunekaer** [comment]
I have requested the log from player
