### ISSUE TITLE
[Bug]: Window blocks from Create do not work

### ISSUE THREAD

**Issue by Mikzoru** [XFactHD/FramedBlocks#215]
### Minecraft version

1.19

### Forge version

43.1.52

### FramedBlocks version

6.6.2

### Describe the bug

I'm not sure why these blocks can't be used in framed blocks, as I've tested with other similar blocks that are either transparent, have connected textures, or both (just like the windows from Create), and they all work just fine.

On a semi-related note it would be nice to see window versions of wall boards, panels, and cubes that have a transparent part in the middle and frames that take on the texture of other blocks. (Preferably versions with two vertical panes and one with just one big square or rounded pane).

### How to reproduce the bug

Right click or shift-right-click on a block from the "FramedBlocks" mod with one of the many window blocks from the "Create" mod. If there is no space to place the block in front of the "FramedBlocks" item, nothing will happen. If there is space for the block to be placed, it will simply be placed in front of the "FramedBlocks" item.

### Expected behavior

Blocks from the "FramedBlocks" mod taking on the texture of the Windows from the "Create" mod when right clicked with one of said windows in the player's hand.

**Comment by XFactHD** [comment]
The reason you can't place these blocks in Framed Blocks is that for all blocks that aren't fully opaque (which includes all glass blocks like Create's window blocks) I can't programmatically make sure that they are a full, simple cube. Instead, I rely on those blocks being tagged as "frameable" through a datapack as explained on the CurseForge page of the mod.

I will add the window blocks to that tag in the next update in order to make this work properly. For the time being, you can also add them to that tag yourself via a datapack.

---

Regarding Framed Window blocks, I'm thinking about adding that to the upcoming architecture-focused add-on I'm working on. Please make a new issue with that suggestion and I'll move it to the appropriate repository when it's ready.
