### ISSUE TITLE
[Bug]: place template closes the game on server

### ISSUE THREAD

**Issue by merko83** [XFactHD/FramedBlocks#222]
### Minecraft version

1.16 - UNSUPPORTED

### Forge version

36.2.39

### FramedBlocks version

2.16.1

### Describe the bug

On the server, placing any template causes the game to close. When entering the server again, the template is set.

### How to reproduce the bug

place any template on the ground

### Expected behavior

put the template

**Comment by XFactHD** [comment]
As you may or may not have noticed, 1.16 is unsupported. You also have not given any information that would allow me to diagnose and fix this issue, notably you failed to provide the crash-report and you didn't mention whether the server or client crashes.

Since I will be releasing a critical bug fix for 1.16 shortly, I will leave this open for now. If you can provide the necessary information before the update is released, I may include a fix for it.

**Comment by XFactHD** [comment]
Since the 1.16 update is about to release, I'll close this issue without a resolution as you failed to provide the necessary information in time.

**Comment by merko83** [comment]
Hello, sorry for not sending it sooner, a lot at work. Here I send you the log and the crash
[latest.log](https://github.com/XFactHD/FramedBlocks/files/10419982/latest.log)
[crash-2023-01-15_12.04.34-server.txt](https://github.com/XFactHD/FramedBlocks/files/10419983/crash-2023-01-15_12.04.34-server.txt)
it is in server version 1.16.5

**Comment by XFactHD** [comment]
You're in luck as this is one of the bugs that was fixed in the FramedBlocks 2.16.2 update.

**Comment by merko83** [comment]
ooo great!!! I will not have to rule it out, since it seems to me that it is one of the most special of my project. Muchas gracias

**Comment by merko83** [comment]
do you have a scheduled date? If it is not too much to ask
