### ISSUE TITLE
[Feature]: a bit of everything

### ISSUE THREAD

**Issue by GreenForzeGaming** [XFactHD/FramedBlocks#223]
### Describe the feature

3 tall door
2 wide trapdoor
id love a trapdoor block that is an incased fan that spins for more industrial builds
allot of create support would be amazing!
and allot of natrual decor like benches chairs planters maybe some decorative rocks you can texture yourself,

**Comment by XFactHD** [comment]
> 3 tall door

I currently have no plans to add larger doors as doors are an absolute pain in the ass to implement.

<br>

> 2 wide trapdoor

I don't really see the point of this since you can just place 2 normal ones next to each other and the same point as above applies here as well. I'd suggest looking into the different options of "double door" mods which allow you to open and close adjacent doors and trapdoors with a single click.

<br>

> trapdoor block that is an encased fan that spins

That's more of a texture thing. If Chisel were ported to modern versions, it would have exactly what you are asking for.

<br>

> natural decor like benches, chairs, planters

That's the kind of thing I want to add in the furniture addon I'm still planning.

<br>

I'm gonna close this for now. I appreciate the suggestions nontheless.
As an aside, please keep in mind that one suggestion per issue is always preferable as it allows me to link commits to the issues.
