### ISSUE TITLE
[Question]: framed panel corner

### ISSUE THREAD

**Issue by xinwolfthorn** [XFactHD/FramedBlocks#224]
### Question

for minecraft version 1.16.5, is it even possible to make a corner block for framed slope panel and framed elevated slope panel? i know a corner block for the framed slope slab and framed elevated slope slab can be made with a framed collapsible block..

**Comment by XFactHD** [comment]
FramedBlocks for 1.16 doesn't have any corner blocks for the slope slabs and slope panels. The corner you have made with the collapsible block is also not a real solution because this only works with two out of the four corners, the other two corners will produce a different shape (which is probably would you encountered when you tried to make such a corner for the slope panels with the collapsible block).

Later versions for 1.18 and newer have corners for these blocks but support for 1.16 has been dropped and as such these features will not get backported to 1.16.
