### ISSUE TITLE
Possible support optifine through optiforge?

### ISSUE THREAD

**Issue by emeraldran** [XFactHD/FramedBlocks#23]
so Optifine is not fully closed since someone made optiforge to make them compatible. if you have optiforge and optifine with the mod it could possibly be tested for optifine bugs.

just a note as I don't think it is fully closed like said on issue No. 15

**Comment by XFactHD** [comment]
AFAIK OptiForge is not needed anymore when you are using the OptiFine version intended for the Forge version you have installed.

OptiFine itself is fully closed source. There are ways to get at the source code but I don't want to have anything to do with any possible copyright infringement and I have absolutely no interest in putting time into something I have no use for myself. After all, this is something I made because I wanted this for my own modpack.

Apart from that, after implementing mitigations for the only crash reported with OptiFine, no one has reported any more problems and the core systems where issues of this kind would arise will most likely not change anymore in the lifetime of 1.16.
If you have any issues or crashes that are not marked as known issues on the CurseForge page, please report them properly.
