### ISSUE TITLE
[Bug]: Textures disappear after Minecraft update

### ISSUE THREAD

**Issue by Aviator737** [XFactHD/FramedBlocks#231]
### Minecraft version

1.19

### Forge version

1.16.5 - 36.2.39, 1.19.3 - 44.1.8

### FramedBlocks version

1.16.5 - 2.16.2, 1.19.3 - 7.0.0

### Describe the bug

Framed blocks are not filled with textures after minecraft version update.

![1.19.3](https://user-images.githubusercontent.com/6958547/216819286-685bfa85-f8d3-4096-bb09-986d509bb5f6.jpg)

![1.16.5](https://user-images.githubusercontent.com/6958547/216819363-f206827a-6adf-4657-9ed7-4c41f6722ce5.png)

### How to reproduce the bug

Create world on 1.16.5, place some framed blocks and fill with texture.
Open the world on 1.19.3.

### Expected behavior

Framed blocks are filled with textures.

**Comment by XFactHD** [comment]
This is expected behavior as I had to change the way this data is stored for technical reasons in the initial 1.19 update. Adding a migration system was not a viable option.

When you are updating modded worlds between major versions of Minecraft, you have to expect issues as these big version updates are basically the only times modders can safely make changes that can break worlds.

**Comment by ghost** [comment]
Why would you not include this in the patch notes?

**Comment by XFactHD** [comment]
My assumption at the time was that it's a well known fact that modded worlds rarely survive major version updates since, once again, major version updates are the only time where we can actually safely make breaking changes like that.
