### ISSUE TITLE
[Bug]: Minecraft crashes after placing some framed blocks in water

### ISSUE THREAD

**Issue by Thomaz-Dunningham** [XFactHD/FramedBlocks#243]
### Minecraft version

1.19

### Forge version

forge 40.2.0

### FramedBlocks version

5.11.1

### Describe the bug

When I place some types of framed blocks in water, the game crashes.
eg: framed torch, framed slab edge

### How to reproduce the bug

1. Place a framed torch/famed slab edge touching with water;
2. Minecraft crashes.

### Expected behavior

In the case of the framed torch it should just drop.

But perhaps on the framed slab edge there was no need to drop.

### Additional details

I only tested with these 2 but maybe there are more.

### Crash log

<script src="https://gist.github.com/Thomaz-Duningham/ba517f1f17e3a18358020529e24254a9.js"></script>

**Comment by XFactHD** [comment]
I could reproduce the issue with just the description in this case, but please make sure to put the whole crash report on https://gist.github.com instead of just a part and make sure the version of the crash report and the version you specify in the issue match (the crash report you pasted is from 1.18).

Fixed version will be released on CurseForge shortly.
