### ISSUE TITLE
MacOS Optifine crash

### ISSUE THREAD

**Issue by ghost** [XFactHD/FramedBlocks#25]
This seems to only happen on mac and doesn't appear to be a Minecraft crash. Hopefully this is an issue which can be fixed.

This crash is uncommon although when the game does crash, however persistent until I load the server/world with Optifine disabled.

[hs_err_pid9571.log](https://github.com/XFactHD/FramedBlocks/files/6463100/hs_err_pid9571.log)

**Comment by XFactHD** [comment]
Which version of Minecraft, Forge and FramedBlocks are you using?

**Comment by ghost** [comment]
1.16.5, Forge 36.1.16, Optifine G8_pre12 (Optifine G7 still has this issue)
I'm using FramedBlocks 2.7.2

**Comment by XFactHD** [comment]
Unfortunately there is nothing I can do about this because I don't have access to a Mac for testing and also because this type of crash is extremely hard to debug and fix.

For now you should be able to mitigate this yourself by disabling the ghost block rendering in the FramedBlocks-client.toml client config.
