### ISSUE TITLE
[Feature]: Centered Vertical Slab

### ISSUE THREAD

**Issue by Flintley** [XFactHD/FramedBlocks#256]
### Describe the feature

It would be very if you could add a slab which is vertical and centered.
I want to build a windmill with the mechanical bearing the create mod and for the two bottom lines I used the skew slab (dont know the exact name). Anyway, for the top line I wanted a centered vertical slab which is not at the right or left side of the block. For now I used double walls  but it would be nice if you would add my suggested block. If you want to I can send a picture of my Windmill so you get a better understanding. And sorry for my bad English.

**Comment by XFactHD** [comment]
I can see how that would be useful, I'll add it to the list. I'd still be interested in seeing your specific use case.

**Comment by Flintley** [comment]
OK when I'm back home I will upload a picture.

**Comment by Flintley** [comment]
![2023-04-20_20 15 37](https://user-images.githubusercontent.com/111710468/233452911-921912c6-9e17-44eb-b10f-9ffee578e934.png)

Thats just a very basic design of my idea. 

![2023-04-20_20 16 53](https://user-images.githubusercontent.com/111710468/233453618-6e424a99-aa4f-41a9-a4eb-fb9bc0ee7c4f.png)
Here you can see that the walls aren't so pretty like a centered vertical slab would be.

**Comment by XFactHD** [comment]
Ok, I can definitely see that making sense. For now until these blocks are implemented you can instead place an additional wall on either side of the "rotor blade" in order to get wall segments without pillars on the blocks you currently have, right click those blocks with the Framed Key to "lock" them (holding the Framed Key and looking at the blocks will show you an overlay with a bit more info) and then remove the additional wall blocks again.

**Comment by Flintley** [comment]
Thanks, I'll try it tomorrow. When do you think the block will be in the new update?

**Comment by XFactHD** [comment]
No idea yet. I'm currently in the process of implementing another set of blocks, which will take a decent amount of time.

**Comment by Flintley** [comment]
OK, then I'll use the walls...
