### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by DreamDuster** [XFactHD/FramedBlocks#259]
### Describe the feature

Version: 1.16.5
Add an option to disable users from getting framed blocks when the block is broken (config file)
Add an option to disable users from being able to right click the specific framed block such as a framed sign from removing the material on the sign (config file)

**Comment by XFactHD** [comment]
What would be the point of these config settings? Why are they needed?

Removing the drops would best be done with a datapack that overwrites the respective loot tables. Doing that with a config setting is unnecessarily complicated.
Disabling camo removal for certain blocks feels like a shotgun solution to a very specific and narrow issue that unnecessarily cripples these blocks in all use cases.

**Comment by DreamDuster** [comment]
The second one is needed because I can't find a more signs mod for 1.16.5, and was thinking of a way to use the "Framed Signs" as different item signs which if the user hasn't crafted the "Framed Sign" I don't want them to be able to get a free left over framed sign that exists as a block, it doesn't have to be every block, thought it would be nice just to have an option to disable it for framed signs as I was going for more of a sign aesthetic type of MoarSigns mod which was for 1.12.2 only

**Comment by XFactHD** [comment]
So if I understand it correctly, you essentially want to be able to have the items drop with the camo stored on them instead of being separated into the item drop (i.e. the Framed Sign) and the camo drop (i.e. a wood plank). If that's the case, then I misunderstood you earlier and removing those drops with a datapack is not possible.
Apart from the fact that 1.16.5 is not supported anymore (this would have only been considered for 1.19 and later), this is a feature that goes completely against the whole design of this mod and would require major internal changes to allow combining blocks with their camo before placement which outwheigh their benefits significantly. I honestly also do not see the relevant difference between having a player place a sign and then apply a camo and a player placing the sign with the camo directly applied to it.

If this is not what you meant, then please go into more detail.

**Comment by XFactHD** [comment]
Closing due to lack of feedback. I'm going to assume that you have no additional no additional details to add to this suggestion.
