### ISSUE TITLE
[Mod Support]: Kitchen block functionality of CookingForBlockheads 1.18.2

### ISSUE THREAD

**Issue by xFirefalconx** [XFactHD/FramedBlocks#261]
### The mod to integrate with

Cooking for Blockheads

### Describe the feature

Cooking for blockheads connects kitchen blocks with another. Their flaw is that there are no carpet-like blocks that can be used to cover up hoppers while let items fall through, for example and make them look and function like kitchen blocks to connect kitchen blocks to another. I can use this mod to make up for the look, but the functionality gets a bit lost, hence the request to make things compatible. 
I don't know if their mod is open source, but I would love to hear back from you regarding this. 
My special request is to make this available on Minecraft 1.18.2, Forge 40.2.0 because I would like to implement this in my modpack in the next update. (Or if it takes a bit longer, in a later one)

**Comment by XFactHD** [comment]
I'm not intimately familiar with Cooking for Blockheads, so I'm not totally sure about the use case. I would appreciate it if you would send a screenshot with an example of what you are referring to and how that makes a difference in terms of gameplay.

A quick glance at their API suggests that this *should* be possible but may have some downsides due to how FramedBlocks is implemented, specifically due to re-using the same underlying blockentity type (a blockentity being the thing that stores the camo data) for most of its blocks.

I'm also going to have to disappoint you regarding the version: the 1.18 version is in maintenance mode and will only receive critical bug fixes but no new features. Supporting more than two versions at once (1.19.2 and 1.19.4 at the moment) is simply not feasible.

**Comment by xFirefalconx** [comment]
Alright, then I don't really have need for an enhancement anyways as I won't upgrade the modpack to 1.19. 

Basically the idea was to have a kitchen where you have a bunch of hoppers underneath that push used or not needed vegetables into composters so you have bone meal for the crop farms. The hoppers look ugly and you get stuck in though so I want to use carpet-like replacements. If I plaster the whole kitchen with those, it could benefit potentially from having the CFB connectivity of the blocks, so you can access your fridge downstairs or the sort. But I will find a workaround then, probably less error prone as well. At least I don't have to use carpets that look strange in a kitchen now, when using this mod.

**Comment by XFactHD** [comment]
As far as I can picture it from your explanatation, that may not work even if the relevant framed blocks did act as "kitchen connections" due to the way the algorithm that searches all connected blocks is implemented and vanilla hoppers not being considered "kitchen connections" as far as I can tell.

The concern I have with just marking all framed blocks as "kitchen connections" is that it's a completely hidden behaviour people may not expect, may be unwanted when you want to have two separate kitchens in an area with lots of framed blocks and it may also cause technical issues.

If you consider this of no use to yourself due to the version limitation I mentioned, then I'd be in favor of closing this as not viable.
