### ISSUE TITLE
1.19.2 Rendering [Bug]: Z-Fighting with Obsidian Pressure Plate

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [XFactHD/FramedBlocks#262]
### Minecraft version

1.19

### Forge version

43.2.8

### FramedBlocks version

FramedBlocks-6.8.3.jar

### Describe the bug

Your ``Obisidian Pressure Plate`` is Z-Fighting.
![2023-04-24_21 27 08](https://user-images.githubusercontent.com/10351221/234160303-129d2fd4-5de9-4c67-9e78-754e83207c6a.png)

### How to reproduce the bug

Make framed obsidian pressure plate and a wood plank.

### Expected behavior

No z-fighting.

### Additional details

None.

### Crash log

None.

**Comment by XFactHD** [comment]
This bug is only possible under very specific circumstances related to specific mods and may not be fixable. Please provide a mod list, preferably in the form of a debug crash report pasted on https://gist.github.com. To create a debug crash report, press and hold F3+C until the game crashes (this also works in the main menu).

**Comment by P3rf3ctXZer0** [comment]
Okay will do.

**Comment by P3rf3ctXZer0** [comment]
Apologies I forgot to do what you asked and since my last update I changed something in rubidium and it fixed itself. (Closing this until I can narrow it down more.)

**Comment by XFactHD** [comment]
That sounds somewhat promising. Please keep me updated if you find it, the fact that a setting fixes it may indicate that there is a way to properly fix this.
