### ISSUE TITLE
suggestion/s

### ISSUE THREAD

**Issue by emeraldran** [XFactHD/FramedBlocks#27]
Vertical stairs. like stairs but on their vertical axis like a corner of a wall. 
vertical slopes. slopes but vertical

Maybe support for glass and or leaves

**Comment by XFactHD** [comment]
What version of FramedBlocks are you using?

Vertical Stairs can already be achieved with the corner pillar and I am thinking about adding a slab corner to make that easier to integrate that.

Vertical Slopes are a thing already. If you target a wall when placing the slope, the slope will be vertical. The ghost block rendering should have given you that information.

Glass and Leave blocks should be useable in framed blocks. If you not, you can add them via a Tag. More details on that will be added to the CurseForge page when I get the time.

**Comment by funAlways** [comment]
Since the thread is here, I'll suggest a horizontal fence/pillar, maybe thinner ones (for railings). Maybe a 45 degree rotated version too for both railings and fences.
Bevel shapes would also be nice.

**Comment by XFactHD** [comment]
I am not really sure what you mean with horizontal fences and pillars. Can you draw up a sketch of what you would intend that to look like?

Rounded bevel shapes are not feasible because they would require ridiculous amounts of faces.
45 degree bevels are essentially what the slope and slope corners are intended for (smaller sloped egdes don't fit the Minecraft aesthetic in my opinion).

**Comment by funAlways** [comment]
It's just fences but horizontal (placed against the wall), making it look like a railing. It's something like [this lattice mod screenshot ](http://www.img2.9minecraft.net/minecraft/img/Lattice-Mod-2.png), although it doesn't connect to adjacent blocks unlike fences. It'll be like the Slab Edge shape, but centered on the block instead of being on one corner.
(Although, lattice shapes would be nice too now that I think about it, if that's feasible). 
Unless I missed something and it's already a thing?
Fair enough about the bevel, yeah I know rounded ones aren't feasible and was thinking of 45 degree bevel with smaller slope (like the two bottom green ones from [this image](https://media.discordapp.net/attachments/735474034774507561/778597932852314152/5EF9AF7A17EB70E9CB3675176D1756BB3CE907F8.png?width=497&height=468)). But I just realized it might look weird with minecraft textures as well.

**Comment by XFactHD** [comment]
I will have a think about the lattice shapes.

**Comment by XFactHD** [comment]
The slab corner block has been implemented in b44fa6b3a9292301ca31a48b7d9d5286f5a6b33c.
The lattice block has been implemented in b83bb7db70c062952a56b6601c4f4243a572c6ed.

Stair railings (especially angled ones) are out of the question due to complexity and not really fitting the mod's theme of mostly simple building blocks.
