### ISSUE TITLE
 dragon can't destroy block

### ISSUE THREAD

**Issue by CreativeManul** [XFactHD/FramedBlocks#270]
### Describe the feature

Hello. Sorry for bad English. Maybe make blocks that the edge dragon can't destroy? For decoration and built in Ende!

**Comment by XFactHD** [comment]
Making all blocks immune to the dragon is unfortunately not possible as it would require duplicating every single block from this mod in order to add the copy to the relevant block tag.

The only thing I can do is to add a single cube that is specifically immune to the dragon as its sole purpose.
Would that satisfy your request?

**Comment by CreativeManul** [comment]
Yes! In fact, three things are always enough for an ideal design - blocks, stairs and hatches) So even just having blocks is amazing!

**Comment by XFactHD** [comment]
I'll add the block to the list of planned blocks then.

**Comment by XFactHD** [comment]
After digging into it, I found a better way to approach this problem, so a new block won't be added for this. Instead, the block's camo and whether it is reinforced will be taken into account when the dragon tries to break a framed block. Since the Framed Reinforcement acts like an obsidian block, it automatically makes the block dragon-proof.
