### ISSUE TITLE
[Bug]: One-Way Window causes translucent blocks to not render properly

### ISSUE THREAD

**Issue by kevindery** [XFactHD/FramedBlocks#276]
### Minecraft version

1.19

### Forge version

43.2.8

### FramedBlocks version

6.8.3

### Describe the bug

When looking to Frame Cube trough Framed One-Way Window only half render.
![2023-06-06_07 02 54](https://github.com/XFactHD/FramedBlocks/assets/50062694/bb42d508-b52f-42e0-a43e-121f34a1fd9f)
![2023-06-06_07 03 15](https://github.com/XFactHD/FramedBlocks/assets/50062694/f0d8c3b8-9ceb-4477-8780-80b09624b79f)

### How to reproduce the bug

looking trough the One-Way Window

### Expected behavior

Render all Framed Cube through One-Way Window

**Comment by XFactHD** [comment]
I'm gonna need a bit more info for this one:

- Which block is used as the camo of the One-Way Windows?
- Which block is used as the camo of the problematic Framed Cubes (I'm assuming water)?
- What's the relative position of the One-Way Windows and the Framed Cubes (a crude top-down drawing would be extremely helpful)?
- Please provide a mod list (hold F3+C until the game crashes (also works on the main menu), put the resulting crash report on https://gist.github.com and provide the link to it)
- Are you using any mods that modify the games rendering (Rubidium, Oculus, OptiFine or similar)?

**Comment by XFactHD** [comment]
I have finally been able to reproduce this and found that this is caused by Rubidium. The same issue happens with the vanilla Tinted Glass block and vanilla Water, meaning this is not specific to the One-Way Window.

You'll need to report this issue to Rubidium instead, with a note that this also happens with just vanilla blocks in this placement.
