### ISSUE TITLE
[Bug]: Does not accept transparent glasses from the wallpapercraft mod - A fresh roll

### ISSUE THREAD

**Issue by Hoglin100** [XFactHD/FramedBlocks#279]
### Minecraft version

1.18

### Forge version

40.2.0

### FramedBlocks version

5.11.5

### Describe the bug

I want to update the church as it would look like in 3018 in minecraft. But when i tried to place a glass block from the wallpapercraft - a fresh roll mod, i could not place it in the framed slope, I clicked, but the glass block was simply placed on the ground. Fix it. Minecraft version 1.18.2

### How to reproduce the bug

Take a block of glass from the wallpapercraft - a fresh roll mod and it Does not fit in the framed slope 

### Expected behavior

I thought that i would take this block of glass from the wallpapercraft - a fresh roll mod and put it in a framed slope and everything would be fine

**Comment by XFactHD** [comment]
Due to technical limitations, I cannot automatically determine whether a non-opaque block like glass is a full cube. For that reason, there is the `framedblocks:frameable` block tag which allows you to mark additional blocks as being allowed in framed blocks with a datapack. This can be done through a proper datapack, through the mod adding the blocks or through tools like CraftTweaker or KubeJS. For hopefully obvious reasons I cannot natively support all such blocks from other mods, mainly because it would become a maintenance nightmare very quickly.

Apart from that I will also note that support for 1.18 has been dropped except for critical issues such as crashes.
