### ISSUE TITLE
Framed Pressure Plates seem to not work on server?

### ISSUE THREAD

**Issue by Erysch** [XFactHD/FramedBlocks#28]
Playing this in the mod pack" Enigmatica E6 0.4.14" (replacing BlockCarpentry):

The framed pressure plates do not open my doors (playing on a server).
Does this happen to you as well?

I don't know if this is a cross mod problem.

I made it work at a sudden point but could not recreate it.

**Comment by XFactHD** [comment]
I can't reproduce this on a dedicated server in the dev environment. What version of Forge and FramedBlocks are you using?

**Comment by Erysch** [comment]
Hey,

am using Forge 36.1.16 and FramedBlocks 2.7.2.

**Comment by Erysch** [comment]
Ok,  I found out: It seems that this only works in one direction
![Base Profile Screenshot 2021 06 09 - 15 48 24 24](https://user-images.githubusercontent.com/81813584/121366995-3803ee80-c93a-11eb-94fa-68e296fc8a80.png)
here it opens normally
![Base Profile Screenshot 2021 06 09 - 15 48 28 89](https://user-images.githubusercontent.com/81813584/121367005-39351b80-c93a-11eb-9485-62ef4d51f496.png)
here it does not

same for a vanilla wooden door:
![Base Profile Screenshot 2021 06 09 - 15 55 46 92](https://user-images.githubusercontent.com/81813584/121368521-6c2bdf00-c93b-11eb-8c8a-e7962d865e9d.png)
![Base Profile Screenshot 2021 06 09 - 15 55 38 59](https://user-images.githubusercontent.com/81813584/121368531-6d5d0c00-c93b-11eb-8cce-09a521cf49f7.png)
![Base Profile Screenshot 2021 06 09 - 15 55 41 52](https://user-images.githubusercontent.com/81813584/121368538-6e8e3900-c93b-11eb-869f-b854b134f0e4.png)
![Base Profile Screenshot 2021 06 09 - 15 55 44 86](https://user-images.githubusercontent.com/81813584/121368543-6fbf6600-c93b-11eb-87b1-66a0ac291bbe.png)

**Comment by XFactHD** [comment]
I updated my workspace to that specific Forge version and I still can't reproduce this issue on a dedicated server.

I looked through the mod list of that modpack and couldn't find any mod that could be interfering with this. Because the Framed Pressure Plate is basically a vanilla pressure plate with the FramedBlocks features on top, I don't see how this can happen. Can you reproduce this same behaviour with vanilla pressure plates?

Basically the only option we have left to find the root cause is for you to perform a binary search:

1. Take out one half of the mods and set it aside (FramedBlocks must stay installed obviously)
2. Try to reproduce the issue
3. If you can reproduce it, repeat step one with the current set. If you can't reproduce it, try again with the other half
4. Repeat this until you can't reproduce it anymore with either half

If you find anything, please report back and I will try to fix it.

**Comment by NielsPilgaard** [comment]
I can't reproduce it in Enigmatica 6 either.

**Comment by XFactHD** [comment]
Thanks for the heads up, that makes this even stranger.

**Comment by XFactHD** [comment]
@Erysch I have published a new version of FramedBlocks. Please try to reproduce this issue with the new version and if you can still reproduce it, please provide a forced crash log from the client and a full mod list from the server via gist.github.com or pastebin.com.

**Comment by Erysch** [comment]
> @Erysch I have published a new version of FramedBlocks. Please try to reproduce this issue with the new version and if you can still reproduce it, please provide a forced crash log from the client and a full mod list from the server via gist.github.com or pastebin.com.

Hey, thanks for your work. I will try it any time I can. I made a note.

**Comment by Erysch** [comment]
> I updated my workspace to that specific Forge version and I still can't reproduce this issue on a dedicated server.
> 
> I looked through the mod list of that modpack and couldn't find any mod that could be interfering with this. Because the Framed Pressure Plate is basically a vanilla pressure plate with the FramedBlocks features on top, I don't see how this can happen. Can you reproduce this same behaviour with vanilla pressure plates?
> 
> Basically the only option we have left to find the root cause is for you to perform a binary search:
> 
> 1. Take out one half of the mods and set it aside (FramedBlocks must stay installed obviously)
> 2. Try to reproduce the issue
> 3. If you can reproduce it, repeat step one with the current set. If you can't reproduce it, try again with the other half
> 4. Repeat this until you can't reproduce it anymore with either half
> 
> If you find anything, please report back and I will try to fix it.

And this one I haven't done yet. Will do that as well.
