### ISSUE TITLE
Support for Diagonal Fences Mod

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#29]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Framed Blocks v2.8.0`
[`Diagonal Fences v1.0.5`](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences)

The Diagonal Fences mod mostly works with the Framed Fences, but it will not visually connect. Is compat for this possible?

![2021-06-20_00 53 45](https://user-images.githubusercontent.com/12000593/122663764-6a93bf80-d162-11eb-91f7-ecd073decdd9.png)

**Comment by XFactHD** [comment]
Compat for DiagonalFences is theoretically possible though in practice it's most likely going to be pretty ugly because I would need to access code in DiagonalFences that is not exposed via an API and can therefore not be considered as stable over long term.

I will look into the feasibility of this and get back to you. Should this not be doable in a maintainable way, then I will add the Framed Fences to the exclusion Tag from DiagonalFences in order to avoid any confusion in the future.

Pinging @Fuzss in case you have any input on this.

**Comment by WenXin20** [comment]
Ah, thanks for looking into it!

**Comment by Fuzss** [comment]
Hi there, I've just pushed an update for Diagonal Fences which includes fences from Framed Blocks in the exclusion tag for now. 
If you want to work on compat I'm happy to make whatever changes you need on my end.

**Comment by XFactHD** [comment]
Thanks for the heads up.
At a first glance, the only thing I need is to have the BlockState properties declared as API. Then I can generate the quads without having to worry about accessing internals.

EDIT: just checked and saw that you did exactly that a few hours ago, that should be enough to make this work 👍

**Comment by XFactHD** [comment]
This was far easier than I assumed in the beginning.

**Comment by Fuzss** [comment]
Wow, nicely done!

About the tag, I just did a quick test and it's working fine...
But it only prevents newly placed fences from connecting diagonally, maybe you still had some old ones?

**Comment by XFactHD** [comment]
I opened an issue about it on you repo ;)
