### ISSUE TITLE
[Bug]: FramedBlocks' glowing blocks don't work with Starlight

### ISSUE THREAD

**Issue by unweeked** [XFactHD/FramedBlocks#294]
### Minecraft version

1.19

### Forge version

43.2.21

### FramedBlocks version

6.8.4

### Describe the bug

When both, Starlight (v1.1.1) and FramedBlocks (v6.8.4) are installed, glowing Blocks stop working when relogging into the world. At first, they work perfectly fine, after a relog however, only the inner of the Frame will be lit up. Not quite sure if you are able to fix that since it seems that the issue is rather on their side, but maybe you can do something about it :D (their github has been real quiet for a month or two)

### How to reproduce the bug

^

### Expected behavior

Glowing blocks should emit light even after the player relogging into the world.

**Comment by XFactHD** [comment]
I've finally had a chance to look into this issue. While I can reproduce it, there is unfortunately nothing I can do about it due to the way Starlight works. Any fix that would technically fix the issue would in practice break existing worlds, not actually fix it in half of the cases or outright break the game (i.e. crash or deadlock it) or any combination of these three.
