### ISSUE TITLE
[Bug]: Grass blocks not appearing as intended when used in framed blocks. 

### ISSUE THREAD

**Issue by Countermoon** [XFactHD/FramedBlocks#295]
### Minecraft version

1.2

### Forge version

47.1.3

### FramedBlocks version

9.0.3

### Describe the bug

Using grass blocks creates a glitched texture on every type of framed block I've tried using them on.
tested with and without resource packs, and shaders, result is always the same. 
![2023-08-06_12 00 42](https://github.com/XFactHD/FramedBlocks/assets/141573156/134b6abf-79f4-4005-b822-05906e88dbab)

### How to reproduce the bug

Place a grass block inside of any framed block

### Expected behavior

Expected to have the grass block texture function as intended when placed in a framed block

**Comment by embeddedt** [comment]
Just to check: does this occur without Rubidium (if installed)?

**Comment by XFactHD** [comment]
This is a known issue with Rubidium's and/or Rubidium Extras' biome blending implementation.
The latest update of Rubidium should have some significant improvements on that front as far as I'm aware.

If you have Rubidium Extras installed, please try removing that first. If that doesn't fix it then try updating Rubidium to 0.7.0a or, if you can't update to that yet due to other mods, disable biome blending in the video settings for the time being.

Please let me know which option fixes it for you.

**Comment by Countermoon** [comment]
Updating Rubidium to 0.7.0a caused my game to consistently crash for some reason. 
Tested all of the methods you mentioned and simply disabling biome blend was the way to solve the issue.
Thank you so much for the solution, and for all the work you have put into this mod. It is simply amazing and I love it <3

**Comment by XFactHD** [comment]
Rubidium 0.7.0a causing crashes is something I almost expected. That update made huge changes, which currently breaks a few mods until they have a chance to update. My suggestion would be to wait a few weeks and then try updating Rubidium again, I just did a quick test in the dev environment and Rubidium did indeed fix this issue.

I appreciate the kind words, happy you like the mod :)
