### ISSUE TITLE
[Question]: Can't get some blocks into framed blocks?

### ISSUE THREAD

**Issue by 34486** [XFactHD/FramedBlocks#299]
### Question

Hello, I have looked and looked for this question but can't find it; how can I get certain blocks such as "Glaxx" (A glass) from xtonesreworked mod to go into framed blocks? I cant find any tag or info about it, its just a block so I thought, I don't think its a tile entity. I can't seem to figure out what to do about this. I saw nothing in config options that will let me blacklist or whitelist blocks.

I am on Forge 43.2.7 (1.19.2) with 6.8.4 of Framed Blocks. 

Thank you.

**Comment by XFactHD** [comment]
You are correct that Glaxx from XTones-Reworked is a "dumb" block and does not have a tile entity (or `BlockEntity` as we call them nowadays). If it had a BE, then you would have gotten an appropriate message.

The issue is that for blocks that aren't fully solid, I can't programatically determine whether they are actual full cubes. For that reason, the affected blocks must be tagged with the `framedblocks:frameable` block tag. You can find the default content of the tag [here](https://github.com/XFactHD/FramedBlocks/blob/1.20/src/generated/resources/data/framedblocks/tags/blocks/frameable.json). The quick solution on your end would be to add the relevant blocks to the aforementioned tag with a datapack. The correct solution is to have XTones-Reworked add their blocks to the appropriate Forge tags so they are automatically included through the default values of my tag. The important parts of this are also documented in the "Datapack Features" section on the CurseForge page of FramedBlocks.

I hope this clears up any confusion.

**Comment by 34486** [comment]
Yes, this helps out. Thank you for your time and information on this. I will try to get in touch with them to see what they can do on their end of it.

**Comment by RiscmonIngk** [comment]
would you be able to produce some sort of tutorial on this procedure?

**Comment by XFactHD** [comment]
The wiki pages about [Datapacks](https://minecraft.wiki/w/Data_pack) and [Tags](https://minecraft.wiki/w/Tag) together with the [existing tag](https://github.com/XFactHD/FramedBlocks/blob/1.20/src/generated/resources/data/framedblocks/tags/blocks/frameable.json) in FramedBlocks should provide you with sufficient information to create a datapack that adds additional blocks to the `framedblocks:frameable` block tag. The internal names of the blocks can be found by placing the blocks in the world and then looking at them with the F3 overlay enabled.
