### ISSUE TITLE
CTM Mapping Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#3]
`Minecraft v1.16.5`
`Forge v36.0.13`
[`CTM v1.1.2.6`](https://www.curseforge.com/minecraft/mc-mods/ctm)
`Framed Blocks v2.1`

When I have the CTM mod installed alongside my [connected textures resource pack](https://www.curseforge.com/minecraft/texture-packs/mc-connected-ctm), the framed blocks sometimes use the ctm map incorrectly. For example, I have a chiseled stone bricks have a pillar texture when multiple are placed together. In the image on the left is the framed block, and the on the left is how it should look. Is it possible to fix this to at least display the original texture? It doesn't have to connect if connected textures are out of scope.

![2021-02-05_15 22 50](https://user-images.githubusercontent.com/12000593/107090775-54462200-67c6-11eb-949b-e85398c8f261.png)

**Comment by XFactHD** [comment]
I will check if I can do something about this.
I have tried to include full CTM support but had to scrap that plan due to complexity.

**Comment by WenXin20** [comment]
Thanks! I appreciate it.

**Comment by XFactHD** [comment]
The CTM textures being incorrectly mapped will be fixed in the next version.

I also managed to add CTM support on the faces that are on the outer edge of the block and occupy the full block size.
Your chiseled stone CTM won't work though (for now atleast) due to the way it is implemented in CTM itself, it will just show the standard chiseled stone brick texture.

**Comment by XFactHD** [comment]
New version is now pending approval on CurseForge.

**Comment by WenXin20** [comment]
Alright, no problem. Thanks!
