### ISSUE TITLE
[Feature]: Copycat-style texture layout

### ISSUE THREAD

**Issue by TyedeeGit** [XFactHD/FramedBlocks#302]
### Describe the feature

Improved texture generation.
On the left you can see how the current version of this mod handles texture generation for stairs. On the right is what I would expect to see. Instead of "painting" the side of the framed block with the texture from the block inside, I suggest using a similar texture generation method that the Create mod uses for copycat blocks as demonstrated in my images.
![2023-08-31_18 31 43](https://github.com/XFactHD/FramedBlocks/assets/79290235/d3de1fb3-6f31-4031-8e42-3ed9acfb484e)
![Screenshot 2023-08-31 185248](https://github.com/XFactHD/FramedBlocks/assets/79290235/d628140f-93e9-40d4-99e0-d8573e64434e)
![Screenshot 2023-08-31 184550](https://github.com/XFactHD/FramedBlocks/assets/79290235/046861b1-a9c6-418c-bb9a-8b7269a24abf)

**Comment by XFactHD** [comment]
Create's copycat blocks are really clever and when they were introduced I did think about doing something similar in FramedBlocks but I came to the conclusion that it doesn't make sense in the grand scheme for several reasons:

- All vanilla blocks and almost all their equivalents in other mods which are equal to or related to some of my blocks apply the textures the same way I currently do it, so anything else would look out of place. Therefore this would need to be an optional thing anyway
- This approach would only work for a very limited set of shapes. The example you gave with stairs would not work because I don't have access to the inner corner (the top-left red corner of the bottom-right block). Any block with a sloped face would be impossible to do this on
- This kind of texture mapping leads to a significantly higher development complexity with the amount of blocks this mod has
