### ISSUE TITLE
[Mod (Loader) Support]: 

### ISSUE THREAD

**Issue by DCI-Mage** [XFactHD/FramedBlocks#305]
### The mod to integrate with

Fabric Loader

### Describe the feature

I want it to be available on fabric. Nothing else, just that. Use a multiloader api if you are not capable of doing it manually (i.e. Architectury)

**Comment by XFactHD** [comment]
There are currently no plans for a Fabric port. Such a port is a significant amount of work on top of normal maintenance, regardless of whether a multiplatform API such as Architectury is used or not.

Also, assuming incompetence as the reason for why a mod is not multiplatform is incredibly rude. I'm perfectly capable of writing the necessary abstractions, the effort needed just significantly outweighs the benefits in this case and the quality of the mod would likely also suffer from it.

**Comment by TelepathicGrunt** [comment]
@DCI-Mage In case you don't know, multiloader APIs (even Arch) are **NOT** a silver bullet. There's still a heck-ton of work that has to go on behind the scenes to even migrate to multiloader and a ton of pain points that comes with that as well. It took a friend a long time and a lot of hours and pain to even get my own mod migrated to arch due to the amount of events and difference between the two platforms that even arch cannot smooth out easily.
