### ISSUE TITLE
[Bug]: Conflicts with other previously adapted Mods

### ISSUE THREAD

**Issue by RiverHYH** [XFactHD/FramedBlocks#308]
### Minecraft version

1.19

### Forge version

47.1.0

### FramedBlocks version

9.0.3

### Describe the bug

There was an irrecoverable game crash when using framed blocks to build a train from the Mod, Create, in the game version of 1.20.1, which is possible in previous fabric versions.

### How to reproduce the bug

The game will crash after pressing the "Create Train" button on the "Track Station" block from Create. The train built with framed blocks will cause the glitch, and can't get into that archive again.

### Expected behavior

Based on a YouTube video created by Mr. Shalz
[https://www.youtube.com/watch?v=ebGUn4UbiWY](url), it should be adapted well.

**Comment by XFactHD** [comment]
This crash was most likely fixed in FramedBlocks 9.1.0. If you can still reproduce it after updating (make sure to also update Forge to 47.1.3), then please provide the crash report via https://gist.github.com, otherwise there is no way for me to determine what caused the crash.

I'm not sure though what you are referring to with "which is possible in previous fabric versions", FramedBlocks does not have a Fabric version

**Comment by XFactHD** [comment]
I'm going to assume that the suggested solution of updating Forge fixed the issue. If it did not, then please respond with the requested information and I will re-open the issue if needed.
