### ISSUE TITLE
[Bug]: Maps in framed item frame being rendered as map item icon

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#309]
### Minecraft version

1.20.1

### Forge version

47.1.46

### FramedBlocks version

9.1.0

### Describe the bug

When I load my world save, the maps in the framed item frames are being rendered like they're normal items, instead of rendering the maps' terrain image.
![2023-09-19_21 04 21](https://github.com/XFactHD/FramedBlocks/assets/51637996/16da81ac-5fa0-432d-8997-63349b7f85e9)

### How to reproduce the bug

1. Make a filled map.
2. Put it inside of any framed item frame.
3. Closes the world.
4. Loads it.

### Expected behavior

![2023-09-19_21 04 07](https://github.com/XFactHD/FramedBlocks/assets/51637996/74460153-7dd6-4fc4-a9d1-a2909f17dcac)

### Additional details

All mods installed:
![mod list](https://github.com/XFactHD/FramedBlocks/assets/51637996/f314af2a-e078-418b-8016-ba82d835b838)

**Comment by XFactHD** [comment]
I omitted most of the nice-to-have "map in frame" features when I implemented these item frames but I completely overlooked the fact that this would break map rendering after a reload (unless the player has the same map in their inventory).
Since I'll have to go 90% there anyway to fix this, I'm just gonna go the extra mile and implement all the missing features.
