### ISSUE TITLE
[Bug]: Upgrading from Minecraft 1.18.2 to 1.19.2 causes the block data to be lost

### ISSUE THREAD

**Issue by Juliandev02** [XFactHD/FramedBlocks#312]
### Minecraft version

1.19

### Forge version

43.2.23

### FramedBlocks version

6.8.4

### Describe the bug

We updated our Create Train Server to 1.19.2. 
Almost everything works fine, except that all the blockdata's from framedblock's blocks are gone. 
It looks like this: 
![image](https://github.com/XFactHD/FramedBlocks/assets/81520713/17aae53a-9c97-4c6f-a403-f2831f839cbf)

### How to reproduce the bug

Upgrade from Minecraft Forge 1.18.2 (FramedBlocks 5.11.5) to 1.19.2 (FramedBlocks 6.8.4)

### Expected behavior

That all blocks were like in 1.18 and without block data loss
![image](https://github.com/XFactHD/FramedBlocks/assets/81520713/2f0729b2-ea2e-4d6a-acd0-c34db38af5b3)

### Additional details

Installed mods:
![image](https://github.com/XFactHD/FramedBlocks/assets/81520713/834c6d25-a89c-4636-b638-dadb965d59c0)

**Comment by XFactHD** [comment]
The update to 1.19.2 significantly changed the way the camo data is stored, mainly to make it easier to support special camos such as fluids. Due to the assumption that it was common knowledge that worlds can rarely, if ever, be carried over to a newer major version of Minecraft (since that is the only time mod developers can introduce breaking changes), I had not implemented a conversion path. Since trying to carry over worlds from older MC versions appears to be significantly more common than I expected, I'll add a conversion path to avoid the data loss.

**Comment by Juliandev02** [comment]
Thanks!
But how can I use this "patch" for my server? @XFactHD

**Comment by Juliandev02** [comment]
okay i made it.

**Comment by XFactHD** [comment]
> But how can I use this "patch" for my server?

Usually you would wait for the release of a new version containing the fix. I will have a release ready in a bit.
I will note that I can provide absolutely no support for custom builds, so if you run into any issues, then you are completely on your own.

**Comment by XFactHD** [comment]
The new builds with this fix have been released about 12 hours ago.

**Comment by Juliandev02** [comment]
> The new builds with this fix have been released about 12 hours ago.
👍🏻
