### ISSUE TITLE
[Feature]: Facades (in addition to Framed Wall Boards)

### ISSUE THREAD

**Issue by mikerooni** [XFactHD/FramedBlocks#322]
### Describe the feature

When viewing framed wall boards from the side, they stick out by 1/16th of a block.

While that's good (and actually preferred) in some situations, I'd like to have an additional version that is completely flush with the block behind it.

Now I don't know if that's possible model-wise, but if it is, please consider adding that feature.  
To avoid overlapping textures of the facade and the block behind it, the idea I had would be to only allow placing facades on non-solid blocks.

Another idea would be to only render the parts of the facade that wouldn't cover any parts of the block behind it, but that's not at all necessary, as that's probably somewhere between quite hard and almost impossible to implement, let alone in a performant way (at least I assume so, but I'm also rather clueless when it comes to rendering).

**Comment by XFactHD** [comment]
I don't really like the idea of a 0-depth facade block, mainly because it can get confusing very quickly in which block space the block actually is and also because this kind of thing likes to cause z-fighting issues with neighboring blocks (this was an issue in the past with the Framed Collapsible Cube). If you do want this kind of block, then the same effect can be achieved by hammering the Framed Collapsible Block completely flat (the latest versions for 1.19.2 and 1.20.1 make that even easier).

**Comment by mikerooni** [comment]
Ah yeah, that makes sense indeed.  
I think hammering a collapsible block completely flat is a good alternative and perfectly fine for my use case.
