### ISSUE TITLE
[Feature]: Framed slope panel to slope panel block.

### ISSUE THREAD

**Issue by Flousunia** [XFactHD/FramedBlocks#323]
### Describe the feature

Sorry, I'm not great at descriptions but a block that on one side starts at 0,0-0,0.5 then on the other side is 0,0-0,1.

**Comment by XFactHD** [comment]
This is unfortunately not viable because the sloped face of the required shape cannot be represented by a flat quad. You can however achieve this shape with the Framed Collapsible Cube as seen in the screenshot:
![2023-09-27_23 43 47](https://github.com/XFactHD/FramedBlocks/assets/11262040/bdbabd9f-c258-4cdb-912c-dbe62707fb82)
