### ISSUE TITLE
[Bug]: Unnecessary Rendering In Double Blocks

### ISSUE THREAD

**Issue by ghost** [XFactHD/FramedBlocks#329]
### Minecraft version

1.18 - UNSUPPORTED

### Forge version

40.2.1

### FramedBlocks version

5.11.4

### Describe the bug

If a framed slab is placed on top of another framed slab to create a double slab aka full block (in the same block) or when you use a  framed double slope slab you can see unnecessary rendering in spectator mode.

![image](https://github.com/XFactHD/FramedBlocks/assets/58036865/65c7ec9e-e5d8-4ac0-a429-1425109ddd6b)

As can be seen in the image double slope slab has parts of it rendered that cant normally be seen in the creative mode.  

As mentioned before this is the same for the framed slabs that are put on top of another.

### How to reproduce the bug

Place a framed slab on top of another in the same block with arbitrary textures. Go to spectator mode and fly into the block to see the unnecessary rendered textures.

Do the same for framed slope slab.

### Expected behavior

The incline texture inside the framed slope slab and middle horizontal part of the double framed slab shouldnt be rendered. 

### Additional details

I believe this extra rendering causes extra resources to be used.

**Comment by XFactHD** [comment]
This is known behaviour and there is realistically nothing that can be done about it, mainly because any attempt to actually filter these faces out would very likely be significantly more expensive in terms of performance than just rendering them "unnecessarily". You also have to keep in mind that these faces are only unnecessary if the opposing camo is fully opaque (i.e. stone) but as soon as the opposing camo is partially transparent or translucent (i.e. glass, stained glass, leaves, etc.) the faces have to be rendered.
