### ISSUE TITLE
[Mod Support]: Connected glass mod does not support connected textures in framed panels(and possibly others)

### ISSUE THREAD

**Issue by Flakxo** [XFactHD/FramedBlocks#335]
### The mod to integrate with

Connected Glass

### Describe the feature

![image](https://github.com/XFactHD/FramedBlocks/assets/135031240/5d8adb0e-1ed9-45ba-9d40-7aa8e7c12eae)

in order from left to right:

connected glass in framed panels

connected glass in framed blocks

connected glass blocks(non-framed)

it seems like theres partial support for the connected glass mod, or maybe panels dont support any connected textures, sorry if this is the case

**Comment by XFactHD** [comment]
ConnectedGlass only works by pure coincidence on the framed cube. If you place another framed cube without a camo next to one with connected glass as the camo, then the glass on the adjacent framed cube will incorrectly connect to it. If you place another connected glass block next to a framed cube with connected glass as the camo, then it won't connect. If you look at the opposite side of those two framed panels, then you will also see that they connect. The reason for this is that ConnectedGlass doesn't use Forge's appearance API and therefore has no idea whatsoever that my blocks are pretending to be something else. I'll have to talk to the ConnectedGlass dev to get them to implement this API in order to have this work properly. I'll keep this issue open until there's a resolution from their side.

**Comment by XFactHD** [comment]
The latest version of ConnectedGlass supports the aforementioned appearance API as well as a small hook from FramedBlocks and therefore works properly with FramedBlocks now. Due to how this change was implemented on their side, the improved support also extends to Rechiseled. It is worth noting that the offset face (in your screenshot the front face) of the Framed Panel as well as the half-width side faces of it will only connect if you change the `conTexMode` in the `framedblocks-client.toml` config from `FULL_FACE` to `DETAILED` (it currently defaults to the former due to the connected textures support still being a bit flaky in certain scenarios).
