### ISSUE TITLE
[Feature]: Ability to remove crafting for certain framed blocks (through config)

### ISSUE THREAD

**Issue by AAKnightmare** [XFactHD/FramedBlocks#346]
### Describe the feature

Some of the framed block models like blocks with slopes doesnt fit into the vanilla blocky-game, so it would be really nice to have the option of disabling unwanted blocks from this mod. (if possible make this change for minecraft 1.19.2 too :))

**Comment by XFactHD** [comment]
I can absolutely see why this is desired but adding config settings to control the recipes is not the way to achieve it, for one because datapacks are already a type of config and also because this mod has somewhere around 150 unique blocks, which would make for a very bloated and unusable config. The proper solution to this is to use datapacks, KubeJS or CraftTweaker to overwrite/delete the recipes.
