### ISSUE TITLE
[Feature]: Let framed blocks be pushed by pistons

### ISSUE THREAD

**Issue by YourFriendHenry** [XFactHD/FramedBlocks#349]
### Describe the feature

I don't know how viable this is with the more un-vanilla blocks but I'd love it if cubes/stairs/slabs blocks could be pushed by pistons.

**Comment by XFactHD** [comment]
All blocks in FramedBlocks have so-called "BlockEntities" which store additional data about the block like which block's appearance it takes. The vanilla game automatically prevents these kinds of blocks from being moved by pistons in order to prevent catastrophic, potentially world-corrupting issues. Making my blocks moveable by pistons would require circumventing these protections, which is something I don't want to do in this mod. There are other mods like Quark which add the ability to move blocks with BlockEntities but I don't know to what degree they can protect against potential issues, so I won't recommend any particular mod.
