### ISSUE TITLE
[Question]: Phantom Membrane on framed blocks

### ISSUE THREAD

**Issue by PixelBuilderLDL** [XFactHD/FramedBlocks#352]
### Describe the feature

I want to use phantom membrane on framed blocks so I can walk through.
But I can't open the config to enable it.

**Comment by XFactHD** [comment]
What specifically do you mean with "can't open the config" in this case?
The config file is located in `<world folder>/serverconfigs/framedblocks-server.toml`. You should be able to edit that file with any basic text editor such as Notepad on Windows. You may just have to right-click the file and select "Open with" instead of simply double clicking the file.

**Comment by XFactHD** [comment]
Closing due to lack of feedback. I assume the above response answered your question.

**Comment by mcm** [comment]
~Is this setting available in the latest version from curseforge? I don't actually have a server config, I have a client and common config, and the common config only has the setting for fireproof blocks. Is there somewhere else to get a newer version of the mod?~

Nevermind. I actually read what you said and I realized I've been looking in the wrong place.
