### ISSUE TITLE
[Question]: Render Error

### ISSUE THREAD

**Issue by Slayemus** [XFactHD/FramedBlocks#364]
### Question

![{A549921F-B8C8-4085-83B9-0BAEA2F1479A}](https://github.com/XFactHD/FramedBlocks/assets/137778514/9f2504af-9b11-433d-a645-b41763fc2e43)
Is there no way to fix this?🥲🥲

Minecraft version: 1.20.1
Optifine version: I6
Forge version: 47.2.18
Mod version: 9.1.6

**Comment by XFactHD** [comment]
This is caused by using OptiFine with a shader. The fix is to stop using OptiFine and instead replace it with [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) for performance improvements or Embeddium and [Oculus](https://www.curseforge.com/minecraft/mc-mods/oculus) for shader support.
