### ISSUE TITLE
[Question]: Am I allowed to fork this to add my own FramedBlocks in a seperate mod? (ex. curved blocks or whatever)

### ISSUE THREAD

**Issue by DiamondKing9998** [XFactHD/FramedBlocks#373]
### Question

Title

**Comment by XFactHD** [comment]
In principle there's nothing stopping you from forking FramedBlocks, the code is open and the license permits it.
With that being said:

- I'm open to suggestions for new shapes as long as they are viable in terms of the technical architecture of this mod, so if you have any ideas, I am happy to consider adding them to FramedBlocks
- Properly rounded blocks are not viable with the way this mod and Minecraft itself work, which is why I have not and will never add those to FramedBlocks
- You don't need a fork of the whole mod to add additional shapes in a separate mod, the better approach would be to make an addon that uses the API provided by FramedBlocks. The benefit of this is that any player can just add your mod if they are already using FramedBlocks
- If you do insist on making a fork, then I request that you rename your fork and change the mod ID accordingly to avoid any possible confusion and compatibility issues
- This project is fairly complex from a technical standpoint, so keep that in mind if you decide to take up the maintenance burden of a complete fork of this project

**Comment by DiamondKing9998** [comment]
Ok, thanks. I'm starting to learn how to make MC mods (already have a good amount of experience with Java) and I thought expanding upon this mod would be really good for a creative building modpack I'm making.

In addition, I think it would be cool to make either a standalone mod or a FramedBlocks dependency that can auto import custom blocks. For example you could have like block "templates" which are essentially FramedBlocks with stats based on normal MC blocks (like how long it takes to mine and stuff) with a file importer to import textures. I'm pretty sure this doesn't exist but I could definitely be wrong. I also don't know if something like this would even be possible, but it would be cool.

**Comment by XFactHD** [comment]
If you are just starting out with MC modding, then I would highly recommend making an addon instead of taking on the full maintenance burden of a project like this. Before jumping into the deep end on that though, you should make yourself familiar with the modding platform you are using by making something basic first.

With respect to your ideas:

- Making blocks from data is fairly involved to do right and if you add the additional requirements of FramedBlocks on top of that then it becomes unreasonably complicated, if not impossible. At some point I tried making just the model "definitions" (the things that create the different shapes from the camo's model) data-driven and it was a complete mess
- FramedBlocks copies most block attributes from the applied camo(s), how long it takes to mine the block is one of the few it doesn't take into account for technical reasons. I might revisit that at some point though to see whether it's viable now

**Comment by XFactHD** [comment]
I'm gonna close this issue for now. If you have further questions about this, you can also find me on the [NeoForge Discord](https://discord.neoforged.net/).
