### ISSUE TITLE
[Feature]: Framed Double Chests But Easy

### ISSUE THREAD

**Issue by StevenDoesStuffs** [XFactHD/FramedBlocks#383]
### Describe the feature

I saw https://github.com/XFactHD/FramedBlocks/issues/72, and I was wondering if we could have framed double chests but in a nontraditional way. 

Rather than placing multiple single chests and having to figure out how they connect, we could instead have an item called "framed double chest", which upon placing would take up two blocks and just act as a double chest. Similarly, breaking any one of the two blocks would break the entire thing. If you've seen immersive engineering's "engineer's workbench", the placing and breaking mechanics could work something like that. 

Alternatively, we could have a "framed double chest half" block which you'd place two of and then right click some specific face to assemble into a real framed double chest. Breaking either of the blocks would break the entire multiblock structure and drop all the items. 

Thoughts? 

If you'd be willing to maintain something like this, I could implement and submit a PR for it.

**Comment by XFactHD** [comment]
Having a special item for double chests doesn't sound particularly nice from a usability standpoint and having to manually connect two halves with a tool would just be confusing. Apart from that, you'd be so close to properly replicating vanilla double chests with this solution, that you might as well go the extra mile and actually do it properly.

I'll look into it again for 1.20.4 since the capability system has changed significantly now, which may make this simpler to pull off.

**Comment by XFactHD** [comment]
I've finally had a chance to look into this again with the new capability system and as it turns out this is indeed viable now, albeit still sufficiently painful. The next update will include proper double chests.
