### ISSUE TITLE
[Feature]: framed slope to framed sloped pannel/framed extended slope pannel

### ISSUE THREAD

**Issue by almechs** [XFactHD/FramedBlocks#384]
### Describe the feature

i dont know if this has been requested or is being worked on but i hope it gets added 
![2024-02-14_17 57 01](https://github.com/XFactHD/FramedBlocks/assets/160087500/12a70e4d-424c-43e9-bf8e-994a0221aa09)
![2024-02-14_17 57 01](https://github.com/XFactHD/FramedBlocks/assets/160087500/475d08a4-5468-4325-b7f6-50411767fe0e)

**Comment by XFactHD** [comment]
This is unfortunately not viable due to the amount of variants required to satisfy all scenarios:

- The opposite combination with the slopes on the left and the slope panels on the right
- The same two combinations with slope slabs
- All four rotations of the slope panels
- All the above but with the slopes placed horizontally
- All the above as an outer corner as well

I hope you can see how that becomes a problem, especially in terms of usability as a lot of them would need to be discrete blocks. This is already kind of a problem with the Framed Slope Panel Corners which fulfill a similar role to your suggestion, except between two slope panels instead of a slope panel and a slope.
