### ISSUE TITLE
[Bug]: Framed Screwdriver no longer rotates camo

### ISSUE THREAD

**Issue by juisemonk** [XFactHD/FramedBlocks#392]
### Minecraft version

1.20

### Forge version

47.20.2

### FramedBlocks version

9.2.0

### Describe the bug

After updating FramedBlocks mod from version 9.1.6 to 9.2.0, screwdriwer can no longer rorate camo. There was no such issue in previous version. 

### How to reproduce the bug

Update FramedBlocks mod to version 9.2.0 on Minecraft 1.20.1 with Forge 47.20.2. Use any camo on any variant of framed block. Try to use screwdriver to rotate camo.

### Expected behavior

Camo rotates

### Additional details

I play with bunch fo other mods, and updeted a couple of them alongside FramedBlocks, so I tried to downgrade only FramedBlocks back to 9.1.6. Screwdriver works as intended.

**Comment by XFactHD** [comment]
Whoops, I completely overlooked that.

Since 9.2.0 was a very large update and this is not a critical issue (i.e. not a crash or world corruption), I'm going to wait a few days before releasing the fix for this as I expect it to not be the only issue.
For what it's worth, this is a purely client-side issue (the rotation is still applied on the server side) and either going far enough away from the chunk to unload it on the client or rejoining the server or world will fix it.
