### ISSUE TITLE
directional wood blocks and unsupported floor boards

### ISSUE THREAD

**Issue by Deragonis** [XFactHD/FramedBlocks#40]
more suggestions than issues, but i would like to be able to see wood blocks be able to be placed horizontally or maybe rotate to be horizontal with the hammer, shift right clicking maybe? and I feel like the floor boards would work well if they worked similar to carpet? or maybe adding a framed carpet?

**Comment by XFactHD** [comment]
Placing wood with a rotation is not really a good solution, especially in combination with the sloped blocks due to their hitbox being a stair step which could lead to frustration when the wood gets placed upwards in one slope and forwards in the next slope.
Adding the functionality to switch through the states with a tool is something I will look into though, that should be easily doable.

The Framed Floor Board is intended to be a "Framed Carpet", calling it that just felt kinda wrong to me. It should behave identical to the vanilla carpets but I might have missed something. I will check and get back to you.

**Comment by XFactHD** [comment]
As it turns out I tried to be really clever with the Floor Board, I have now changed the Floor Board to be equivalent to vanilla carpets.
For cycling through camo states I have added a wrench item to keep the interaction simpler. This feature is currently limited to certain specific properties but I might expand it a bit before releasing this feature.

**Comment by Deragonis** [comment]
so an idea for the directional wrench now, the ability to rotate the blocks in stacked slabs or other stacked blocks individually, so things like this would be possible
![image](https://user-images.githubusercontent.com/27950401/126899640-1cec3425-9445-4581-be5c-a550f9774bff.png)
