### ISSUE TITLE
[Bug]: Two Item Frames on a single block

### ISSUE THREAD

**Issue by andriihorpenko** [XFactHD/FramedBlocks#401]
### Minecraft version

1.19

### Forge version

43.3.8

### FramedBlocks version

6.8.6

### Describe the bug

Seems like I can place both vanilla and FramedBlocks Item Frame on a single block.
Not sure if this is intended due to z-fighting happening.

https://github.com/XFactHD/FramedBlocks/assets/13716167/aaa54c69-e6d8-44d7-8de1-40598db2e638

### How to reproduce the bug

1. Place vanilla Item Frame
2. Target cursor outside the placed Item Frame
3. Place FramedBlocks Item Frame

### Expected behavior

Prevent placing two Item Frames on a single block (vanilla's behavior)

**Comment by XFactHD** [comment]
This is a vanilla issue, there is nothing I can do about this. For technical reasons, the Framed Item Frame is a block and not an entity. When a vanilla Item Frame is placed where a Framed Item Frame already exists or vice-versa, the one being placed doesn't "notice" the one that already exists since in both cases the placed one doesn't have a collision bounding box. The same exact issue also happens with vanilla blocks that don't have collision, you can for example place an Item Frame and a Sign on the same block face since one is an entity and the other is a block.
