### ISSUE TITLE
[Feature]: Grass (or any spreadable blocks) spreads over on FrameBlocks 

### ISSUE THREAD

**Issue by IHostic** [XFactHD/FramedBlocks#404]
### Describe the feature

This would be nice feature so you don't require silk touch to get a grass block and dirt can just become grass (or any block can spread towards a framed blocked) (animals can eat from it) and adds lots of possibilities to the mod.

**Comment by XFactHD** [comment]
This is unfortunately not possible due to how grass spreading works (mainly because the system expects the relevant block to actually be there and not a "random" block that just imitates it) and making every framed block have random ticks enabled just in case someone places a spreadable block in one would also be a performance nightmare. The first point also applies to allowing animals to eat from these blocks.
