### ISSUE TITLE
[Feature]: More framed sloped panel variants

### ISSUE THREAD

**Issue by Marshall2439** [XFactHD/FramedBlocks#422]
### Describe the feature

Hello im trying to make realistic trains in create mod but they need more sloped variants to make it look realistic so here is my suggestion:

Framed Horizontal divided slope panel: Regular sloped panel which is divided horizontally
Framed vertical divided sloped panel: same but vertical
Framed extended horizontal divided slope panel: eame as first one but extended
Framed extended vertical divided slope panel: same as second one but extended

**Comment by XFactHD** [comment]
- Framed (extended) vertical divided slope panel: I assume you mean something like the Framed Divided Slope, in which case this would be included as part of #288 and require finding solutions to the problems mentioned in that issue
- Framed (extended) horizontal divided slope panel: I assume you mean a slope panel which is divided perpendicularly to the slope, which is very unlikely to happen as it is extremely niche
- Framed slope panels with three parts: this is definitely not going to happen, two parts is the limit I have set in order to keep the technical complexity reasonable and also to keep the performance as high as possible

**Comment by Marshall2439** [comment]
By the first one i meant that slope panels are divided like normal slope

**Comment by XFactHD** [comment]
I'm not sure what you mean by that. Can you illustrate what you are referring to (simple drawing suffices)?

**Comment by Marshall2439** [comment]
![Uploading 20240427_083948.jpg…]()

**Comment by Marshall2439** [comment]
This

**Comment by XFactHD** [comment]
The picture unfortunately did not get uploaded properly, please send it again.

**Comment by Marshall2439** [comment]
Okay my bad for not responding for months I will upload better pictures now

**Comment by Marshall2439** [comment]
by the way why is slope divided perpendicular not gonna be added?

**Comment by Marshall2439** [comment]
![20241029_145945](https://github.com/user-attachments/assets/7a97837f-d1ad-496b-8643-0bb17e3147ed)

**Comment by XFactHD** [comment]
Ok, that matches what I had assumed, so we're on the same page here.
For the vertically divided one see the issue I linked above.

> by the way why is slope divided perpendicular not gonna be added?

It's an extremely niche shape and I need to make sure the list of blocks does not get bloated too much as it is already very large.
