### ISSUE TITLE
[Feature]: Cauldrons

### ISSUE THREAD

**Issue by justsomebodynew** [XFactHD/FramedBlocks#424]
### Describe the feature

Would framed cauldrons be possible?

**Comment by XFactHD** [comment]
Theoretically yes, but in practice they would be really annoying to implement and, as soon as a mod has a custom cauldron for one of its fluids, the framed one wouldn't behave the way a user expects as it wouldn't be able to handle the custom fluid due to how cauldrons hold the fluid. For those reasons I won't be adding framed cauldrons.
