### ISSUE TITLE
[Bug]: CRASHING when loading in a block

### ISSUE THREAD

**Issue by Swoofterkitty** [XFactHD/FramedBlocks#425]
### Minecraft version

1.20

### Forge version

1.20.1

### FramedBlocks version

9.2.0

### Describe the bug

I made a  Valkerian Skies airship with framed blocks, after loading it in again, it caused me to crash. no one else on the server is having this issue with the same blocks.

### How to reproduce the bug

Place a (unkown) framed block on a Valkerian skies airship?
Load in, crash

### Expected behavior

not a crash

### Crash log

https://gist.github.com/Swoofterkitty/0cc707ff66f92b902e537bab35ee1e84

**Comment by Swoofterkitty** [comment]
Also tested on 9.2.1, same result

**Comment by XFactHD** [comment]
As far as I can tell, this is caused by Valkyrien Skies causing incorrect data to be provided about the block you are looking at when FramedBlocks renders the placement preview. I'm going to add a check to guard against this nonsensical data. Until the fix is released, you can prevent the crash by disabling the placement preview by setting `showGhostBlocks` to `false` in the `framedblocks-client.toml` config. Keep in mind though that placing any of the Slope Panel blocks will most likely also trigger this crash, potentially even on the server side.

**Comment by XFactHD** [comment]
FramedBlocks 9.2.2 with the fix has been approved on CF and Modrinth

**Comment by Swoofterkitty** [comment]
That fixed it! Thank you!
