### ISSUE TITLE
[Feature]: Framed Redstone Dust

### ISSUE THREAD

**Issue by WenXin20** [XFactHD/FramedBlocks#428]
### Describe the feature

I have been looking for a way to easily hide redstone dust / redstone torches in places that don't have much room to hide redstone.  

My suggestion is to add some kind of redstone dust / torch that can be hidden as a full block and powered by other power sources, like the lever. This would be similar to the Framed Redstone Block, but without it being powered by default like the redstone block is.
The closest example I can think of is the Cog block in Supplementaries, which acts like a full block of redstone dust and can travel vertically. But it is not easy to hide either.

**Comment by XFactHD** [comment]
I try my best to stay far away from redstone because it is a complete mess. Redstone sources and sinks are *mostly* fine, but redstone wires are really hard to get working nicely. Therefore this is unfortunately not going to be added.

Depending on the version you are targetting, one potential alternative would be redstone conduits from EnderIO as those can be hidden in a solid cube with the help of their own facade system.

**Comment by WenXin20** [comment]
Ah I see, that's fair. I have tried integrating redstone function in my own mod before, and it was pretty finicky and annoying to work with.
