### ISSUE TITLE
[Mod Support]: Chipped connected texture 

### ISSUE THREAD

**Issue by Djahmo** [XFactHD/FramedBlocks#436]
### The mod to integrate with

Chipped

### Describe the feature

Make the chipped connected block work with framed block

**Comment by XFactHD** [comment]
Athena integration has existed in FramedBlocks for a while. Please provide information on the versions of Minecraft, FramedBlocks, Athena and Chipped you are using. You may have to set `conTexMode` in `framedblocks-client.toml` to `DETAILED` as it was set to `FULL_FACE` in previous versions of FramedBlocks due to connected textures support not being fleshed out yet in general.

In dev in 1.20.1, Chipped's connected textures work fine on FramedBlocks blocks with Athena 3.1.2 and Chipped 3.0.6:
![2024-05-12_04 47 32](https://github.com/XFactHD/FramedBlocks/assets/11262040/50d8ce48-498e-4f15-928f-e3b3b67960bb)

**Comment by Djahmo** [comment]
> Athena integration has existed in FramedBlocks for a while. Please provide information on the versions of Minecraft, FramedBlocks, Athena and Chipped you are using. You may have to set `conTexMode` in `framedblocks-client.toml` to `DETAILED` as it was set to `FULL_FACE` in previous versions of FramedBlocks due to connected textures support not being fleshed out yet in general.
> 
> In dev in 1.20.1, Chipped's connected textures work fine on FramedBlocks blocks with Athena 3.1.2 and Chipped 3.0.6: ![2024-05-12_04 47 32](https://private-user-images.githubusercontent.com/11262040/329822592-50d8ce48-498e-4f15-928f-e3b3b67960bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MDg4OTksIm5iZiI6MTcxNTUwODU5OSwicGF0aCI6Ii8xMTI2MjA0MC8zMjk4MjI1OTItNTBkOGNlNDgtNDk4ZS00ZjE1LTkyOGYtZTNiM2I2Nzk2MGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEwMDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhZDEyMWM4YjBjN2M3YmE2ZWM4OTNlNWRkNjQ3N2Y4OTBlMjk0MmVkY2ZiMDYyNTMyOTkzMjFhZGFiNDVmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gu8ix7jk3CjeHJq21d_odVKze6_J5dRfEvOOc3Ej030)
 
I have Athena 3.1.4 and Chipped 3.0.4 with all the mods 9 no frills. But i dont have an `framedblocks-client.toml` in my config folder only `framedblocks-common.toml` and Framed block is on the last version

**Comment by XFactHD** [comment]
I just tested this in ATM9 No Frills: the client config file exists and Chipped blocks with connected textures work fine after changing the setting I mentioned. This seems to be an issue with your installation and is as such outside of my control.

**Comment by XFactHD** [comment]
I'm going to assume that you managed to solve the issues that caused this. If you're still running into issues, please respond to this issue and then we can look into it further.
