### ISSUE TITLE
What happens if you use these blocks too much?

### ISSUE THREAD

**Issue by dajiuji** [XFactHD/FramedBlocks#45]
What if I use a lot of these blocks in a block? Will it cause lag or longer time to load the world? Will it crash the block?

**Comment by XFactHD** [comment]
The actual load time will not be impacted, though the first time a chunk is rendered after loading might cause a short lag spike because the models have to be generated. The more different shapes you use (different rotations are handled like different shapes in this case), the more load will be generated when rendering a chunk for the first time after loading.

The amount of blocks will also impact the world size. The world will take up more storage space and also more RAM due to the way the necessary data is stored (though this is not any worse than other mods with data storage in blocks). This should not really be noticeable though unless you use very large amounts of these blocks.
