### ISSUE TITLE
[Feature]: A tool for toggling the texture of block faces of single texture framed blocks.

### ISSUE THREAD

**Issue by SeveringHams** [XFactHD/FramedBlocks#453]
### Describe the feature

So the user would take a screwdriver and smack the face of a framed block, which would make any face that is smacked the secondary material on that framed block. It would only work on **single material framed blocks** because i would imagine having to program in the toggling on the double material ones would be ludicrous and unreasonable. 

Plus, this way it would only add 2 nbt tags (in theory), it would add a ToggledFaces list, and of course, it would have a second camo tag like the two-material framed blocks. I'm sure there's better ways to do it, but I think it would be pretty cool, and it would make train roofs way slicker.

**Comment by XFactHD** [comment]
I'm not sure this is particularly useful considering you can achieve the same effect with clever usage of existing two-material blocks. If there are two-material blocks missing for certain cases, then I would rather add those (assuming they aren't too niche) instead of adding another layer of complexity to the camo application system

**Comment by XFactHD** [comment]
Closing as this provides fairly little benefit at a significant cost of complexity both for the user and in the implementation.
