### ISSUE TITLE
[Bug]:  Glowstone applied to framed blocks only last until server restart

### ISSUE THREAD

**Issue by rCane0714** [XFactHD/FramedBlocks#456]
### Minecraft version

1.20

### Forge version

NeoForge 47.1.84

### FramedBlocks version

9.3.0

### Describe the bug

When a framed block is lighted with glowstone so it gives off light, it stops emitting light after server restart/relog. You also can't reapply glowstone to it.

![2024-06-28_20 26 04](https://github.com/XFactHD/FramedBlocks/assets/36411556/d2c4ea13-919d-4383-913d-0514932fcd05)

### How to reproduce the bug

- Place framed block (doesn't matter if another block is applied or not)
- apply glowstone
- the block emits light
- relog
- the block only emits a tiny bit of light, see screenshot

### Expected behavior

it should keep emitting light

### Additional details

- I'm on FTB D20 1.20
- experimentalForgeLightPipelineEnabled/Disabled is the same
- inside and outside of claimed chunks is the same

**Comment by XFactHD** [comment]
Are you using Starlight?

**Comment by rCane0714** [comment]
Yes, I am using Starlight 1.1.2

**Comment by XFactHD** [comment]
That's what I suspected. Unfortunately it's not possible to fix this due to where this incompatibility comes from. The only solution is to remove Starlight. It's worth noting that Starlight has little to no benefits in 1.20.1 and later due to improvements made to the base game. This was also indicated by the Starlight dev themselves.

**Comment by rCane0714** [comment]
Thanks! That worked.
