### ISSUE TITLE
[Mod Support]: Additional Placements

### ISSUE THREAD

**Issue by K-Proj** [XFactHD/FramedBlocks#485]
Support for the **[Additional Placements](https://modrinth.com/mod/additional-placements)** mod would be a massive time saver.

### What does the requested Mod do?
Additional Placement is a mod that allows a player to place blocks in different orientation using a vector overlay over hovered blocks. This mod not only allows for non-vanilla orientations for blocks, like the Vertical Stairs and Vertical Slabs that FramedBlocks allows for, but it does this without adding any blocks. The vector placement allows for slabs to be horizontal and vertical, same goes for stairs and so on.

### Reason for support
The major reason to add support for this mod would be to clean up Inventory from the various orientation varieties of the same block. 

For instance instead of carrying: 

- Framed Sliced Stairs Slab, 
- Framed Vertical Sliced Stairs,
- Framed Stairs
- Framed Vertical stairs.

A player could just carry:

- Framed Sliced Stairs Slab
- Framed Stairs.

Then allow the Additional Placement mod to take over for orienting the block placement. This example can go on for the several types of blocks in this mod that have different orientations. Having a bunch of different variants of these framed blocks is already a bit cumbersome due to how vanilla MC works with inventory management. The support additional placement would also save time from orienting blocks using the wrench and cycling through.

**Comment by XFactHD** [comment]
Additional Placements does add additional blocks, they are just not visible to the player in the form of items, and as such it's not possible for FramedBlocks to directly make use of the systems in Additional Placements since FramedBlocks needs to retain full control of its blocks for technical reasons. Adding this behaviour to FramedBlocks would require replicating basically the entirety of Additional Placements, which is a significant amount of work I cannot justify and in practice I also don't necessarily want this behaviour, in part because I simply dislike it and in part because the placement behaviour of a bunch of blocks is already complicated enough and in places even confusing and in need of reworking. I have some ideas for making placement of certain blocks a bit easier (see here: https://github.com/XFactHD/FramedBlocks/issues/486#issuecomment-2319816293) and may at some point merge some blocks which really have no good reason to be separate like the wall board and floor board.

**Comment by ABakedWaffle** [comment]
Ah, that is understandable. Thank you for linking me here
