### ISSUE TITLE
[Feature]: Similar functions to AE2 cable anchors for "floor boards" and similarly thin blocks

### ISSUE THREAD

**Issue by ABakedWaffle** [XFactHD/FramedBlocks#495]
### Describe the feature

Features:
1. AE2 cable anchors can be placed in any orientation around a block, and I think it would be neat if blocks for this mod could be done in a similar way, cutting back on crafting recipes and adding more building options

2. Cable anchors occupy the *same space* as the block they're attached to. I'm not suggesting they be attached to the block they would occupy the same space as, but maybe (like water does with some partial blocks) if they could both occupy the same space, that would make builds cleaner
![FramedBlocksPartialExample](https://github.com/user-attachments/assets/8b98c3ab-3eec-4d78-b593-d116bd26ce2f)

3. Connecting block textures! The blocks in the above picture have connecting textures, but FB doesn't allow them to detect each other and connect. Maybe you could implement a system that allows for a single check for the blocks around them upon block update? Like placing a block with the same texture next to it.

I recognize that this is not AE2, and understand that you have your own vision, and that I know virtually nothing about making mods or coding. You have your own vision for this mod and I respect that. I think that the implementation of these features would allow for huge building expansion, and you could change the "floor board" block to a "framed cover", cutting back on crafting recipes as mentioned in "1". The ability to exist in tandem with other "partial" blocks could allow for overlapping the "covers", making it so you could have a complete cover for, say, wall/ceiling corners.

Thank you for considering, ABakedWaffle

**Comment by XFactHD** [comment]
1. I have some plans for improving placement behaviour and potentially merging simple blocks like the floor board and wall board into one since those for example really have no reason to be separate. For any other merging of multiple blocks into one for placement, see my response here: https://github.com/XFactHD/FramedBlocks/issues/485#issuecomment-2319962402
2. That's unfortunately not possible in a generic way, it would either require ever mod to agree on a so-called multipart system that allows multiple different things to exist in a single block space or require FramedBlocks to implement dedicated support for every mod with blocks like those in the picture. The former is very unlikely to happen and the latter is completely unmaintainable
3. FramedBlocks already has sofisticated support for connected textures, but for technical reasons this support needs some assistance from the mod implementing the connected textures. The connected textures not working in the image has one of two causes:
    - The connected textures support is configurable in the `framedblocks-client.toml` config and defaulted to a lower mode of support in earlier versions for 1.20.1 (which I assume is what you are using). Make sure the `conTexMode` in said config file is set to `DETAILED`
    - If changing the config does not help, then I need more information on which mod these specific blocks are from so I can look into what is needed to get them supported

**Comment by ABakedWaffle** [comment]
Thank you! I'll talk with my server's owner. I'm on the Hack the Planet ATM9 server, so I don't have access to the config, but I'll see if that can be worked on

**Comment by XFactHD** [comment]
The config file in question is on your PC and the server has no control over it. You don't need to ask your server admin for permission or the ability to change it.

**Comment by ABakedWaffle** [comment]
Gotcha, much appreciated

**Comment by XFactHD** [comment]
Due to lack of further response I'm going to assume that the suggested config change resolved the connected textures issue.
Since the other suggestions are not feasible, I'm going to close this issue for now.
