### ISSUE TITLE
[Bug]: lighting issue with some blocks

### ISSUE THREAD

**Issue by TrickShotMLG02** [XFactHD/FramedBlocks#497]
### Minecraft version

1.20

### (Neo)Forge version

47.2.20

### FramedBlocks version

9.3.0

### Describe the bug

![image](https://github.com/user-attachments/assets/845aaed0-5a03-4880-89fe-57bd4eaf04c9)
![image](https://github.com/user-attachments/assets/68f582c0-caf3-4f1d-b334-12c9045476d9)
![image](https://github.com/user-attachments/assets/f0c251e4-53b4-4284-817c-d8e38cd883bb)

there is a problem with the lighting of some blocks in the east and west direction. North and south work fine, but the other two sides appear darker. 

### How to reproduce the bug

place 4 framed elevated slope edge blocks in a square and fill them with white concrete

### Expected behavior

There should be no lighting issues and the color should be the same on all sides

**Comment by XFactHD** [comment]
The different brightness between the X (east/west) and Z (north/south) axis is vanilla behaviour and cannot be circumvented.
The actual issue is that the vanilla light pipeline is unable to properly light faces which are not axis-aligned. To fix this, make sure the `experimentalForgeLightPipelineEnabled` setting in the `forge-client.toml` is set to `true`.
This is how this setup is supposed to actually look:
![2024-09-05_04 20 42](https://github.com/user-attachments/assets/c8c5303a-79ff-4467-8a18-da691f2e051e)
