### ISSUE TITLE
[Feature]: add recipe with texture block

### ISSUE THREAD

**Issue by loulou1310** [XFactHD/FramedBlocks#512]
### Describe the feature

Hello,

I am building a "big" pyramid ([100x100](https://imgur.com/a/3jtWCVf)) and the clicking each block to texture it is getting a bit tedious. I've come recently across of a functionnality in the mod FunctionnalStorage where you can customize any "framed" type of this block using a crafting recipe :
![image](https://github.com/user-attachments/assets/b5f2a49f-b9d1-4168-8724-2043a0f2fdb6)
I was wondering if adding (not changing the way it is now) something like this would be possible for this mod. I think this would make this mod more attractive to the people that like to build with tools like copy/paste or schematic since you would not need to click each block with the texture block anymore for the part that you have already done once and can be replicated (roof, wallsection, floor, stairs, etc).

**Comment by XFactHD** [comment]
In the 1.21 versions FramedBlocks does provide such a recipe. Backporting this to 1.20.1 however is not feasible due to the associated systems working very differently between these two versions.
Copy/paste and schematic tools also wouldn't use these pre-combined blocks since they have no knowledge of the additional data required to correctly replicate the appearance. Instead they need dedicated integration and would then consume the blank framed block and the camo material(s) separately. Create's Schematicannon has dedicated integration since Create 0.5.1g, other mods like Building Gadgets and Construction Wand currently do not as they don't provided the necessary APIs to add such integration.
