### ISSUE TITLE
[Feature]: Make Framed Tube's wall thickness adjustable

### ISSUE THREAD

**Issue by AlisonHuang777** [XFactHD/FramedBlocks#521]
### Describe the feature

As the title suggested. I would like to have a 3-pixel-thick tube to match the thickness of copycat panels.

**Comment by XFactHD** [comment]
I'm really not sure about this. I can see the point with regards to "visual compatibility" with trapdoors and the Copycat Panel, but increasing the wall thickness even just by one pixel breaks the primary idea behind the block: you wouldn't be able to climb through it vertically anymore and crawling into it horizontally also becomes really fiddly because the player's hitbox is 9.6 pixels wide and the tube would only be 10 pixels wide.

**Comment by AlisonHuang777** [comment]
My point is, that's true for players, not for items. The idea of using them as item chutes is also reasonable, isn't it?

**Comment by XFactHD** [comment]
Yeah, that's definitely a fair point, I didn't consider that. I'll add it to the backlog.
