### ISSUE TITLE
[Bug]: Visual Glitch with framed stone plate and water camo

### ISSUE THREAD

**Issue by tomprince** [XFactHD/FramedBlocks#536]
### Minecraft version

1.20

### (Neo)Forge version

47.3.7

### FramedBlocks version

9.3.1

### Describe the bug

![image](https://github.com/user-attachments/assets/69dec154-b5d6-4ae1-bab0-9d851d27338e)

Note stone colored pixels around the corners of the pressure plate.

### How to reproduce the bug

Place a framed stone pressure plate atop a framed cube and apply water camo to both of them.

### Expected behavior

I expect the stone pressure plate to be entirely camouflaged, and not show any stone texture.

**Comment by XFactHD** [comment]
This is not a bug, the stone overlay is intentional. All non-wood pressure plates and buttons as well as a couple full-cube blocks have such a "type" overlay. You can however disable this in the `framedblocks-client.toml` by setting `showButtonPlateTypeOverlay` to false for the pressure plates and buttons and `showSpecialCubeTypeOverlay` to false for the redstone block and bouncy cube.
