### ISSUE TITLE
[Feature]: 1.20.1 corner options for sliced stairs

### ISSUE THREAD

**Issue by RAM-2022** [XFactHD/FramedBlocks#541]
### Describe the feature

I saw in a previous issue that adding the connectedness of the framed sliced stairs would not be possible in 1.20.1, and only in 1.20.6 and onwards. So I wanted to ask if it would be possible to add specific inner and outer corner variants of those blocks for 1.20.1? This give the functionality of merging a slab/panel and a slab corner for outers, and slab and half stairs/vertical half stairs for inners.

**Comment by XFactHD** [comment]
Corner options for the various double stairs (including sliced stairs) are unfortunately not going to happen in 1.20.1, primarily for three reasons:
- 1.20.1 is basically in feature freeze at the moment because I don't have time to deal with backporting large sets of blocks
- This would have to be done for all double stairs blocks for consistency, which is a very significant undertaking
- The new blocks wouldn't have an upgrade path which means that upgrading a world with those blocks to a newer MC version would cause these blocks to vanish
