### ISSUE TITLE
FramedBlocks Crashing on New Building Gadgets Updated

### ISSUE THREAD

**Issue by BedrockLegends** [XFactHD/FramedBlocks#60]
![2021-10-21_18 46 46](https://user-images.githubusercontent.com/48525410/138371731-0116e6f0-efa1-448e-98d3-9ec256b319e1.png)

**Comment by XFactHD** [comment]
That is not a crash. I deliberately limited the support to a very specific version of Building Gadgets because I know that they plan to fix a few issues I worked around in my compatibility implementation and due to the nature of these issue those workarounds would break when combined with a proper fix from their side.

I will check if anything changed in respect to these issues and depending on that adapt to the fixes and update the required version or widen the version requirement. This will have to wait until after a few hours of sleep though.

**Comment by XFactHD** [comment]
After a conversation with the Building Gadgets dev, I decided to remove the upper limit of the version requirement.
