### ISSUE TITLE
Game crashing when placing framed cube

### ISSUE THREAD

**Issue by DeDog103** [XFactHD/FramedBlocks#63]
My friend and I are playing on a slightly modded server. He is the only person to experience this issue so far. Here is the log.
[Redacted]
.

**Comment by XFactHD** [comment]
Tell him to try without OptiFine. If that doesn't fix it, tell him to disable the ghost block rendering in the framedblocks-client.toml config file.

PS: I have removed the log from your initial post because it contains sensitive data. Please tell your friend to log out and then log in again in the MC launcher to renew his access token.
Next time you have a log that is called something like hs_err_pidXXXX, please open it in a text editor, search for `--accessToken` and remove the long string of random letters and numbers following that before posting it.

**Comment by XFactHD** [comment]
I am going to assume that the problem was fixed by the solutions I sent.
