### ISSUE TITLE
Block Entity

### ISSUE THREAD

**Issue by Guildspace** [XFactHD/FramedBlocks#69]
Is it at all possible to make it so tile entities can also be put into framed blocks without using the actual purpose? The example of the block I want to use is the seared bricks from Tinkers' Construct. I love the appearance of them but don't really need to build a smeltery with framed blocks. I try to add it into the framed blocks but it says it cannot be added.

**Comment by XFactHD** [comment]
Yes, this is possible but has a lot of risks involved with it.
Currently the only block with a tile entity that is in the hard-coded list of allowed blocks is the note block because I know that it works.
I am thinking about adding a server config setting for this and making it so blacklisted blocks get removed automatically on load to allow the player to fix a crash caused by a tile entity in a framed block acting up.

**Comment by Guildspace** [comment]
That sounds absolutely lovely! Thank you so much for responding. I love this mod so much so it'd be a lifesaver to have that sort of security function!
