### ISSUE TITLE
Visual glitch when I place blocks?

### ISSUE THREAD

**Issue by FatherPigeon** [XFactHD/FramedBlocks#81]
So I've been using this mod for a while now, and just recently, at best maybe a week ago, whenever I place blocks from this mod it causes a visual glitch and causes water to disappear within the chunk. I've sent screenshots to show what exatly is happening, since this has never caused me to crash or caused any signifigant damage on gameplay, just the visual glitch
Without the block placed
![2022-02-02_09 20 57](https://user-images.githubusercontent.com/98893421/152172774-fa977216-4561-4b76-b1fc-7946becb014d.png)
With the block placed
![2022-02-02_09 21 16](https://user-images.githubusercontent.com/98893421/152172790-74c2b5a4-e9a8-4c57-9835-d12548f0e2ec.png)
This seems to happen with all the blocks from this mod

**Comment by XFactHD** [comment]
I need a lot more details to diagnose this.
Which versions of Minecraft, Forge and FramedBlocks are you using?
Are you using OptiFine, Sodium or any similar optimization mod(s)?

**Comment by FatherPigeon** [comment]
Of course, the current profile I am using is on 1.16.5 Minecraft with Optifine. I'm currently using the latest update of FrameBlocks (version 2.12.0) and Forge 36.2.20

**Comment by XFactHD** [comment]
Can you reproduce this without OptiFine?

**Comment by FatherPigeon** [comment]
Apologies for the wait! It seems to be fine when Optifine is out of my game as shown in the screenshots 
![2022-02-02_22 46 33](https://user-images.githubusercontent.com/98893421/152278207-56ce4a89-5fa7-4bc8-9c83-05deaa72fffa.png)
![2022-02-02_22 46 41](https://user-images.githubusercontent.com/98893421/152278210-c9cfea3f-8344-44e6-8128-171084e763bf.png)

**Comment by XFactHD** [comment]
Then there is unfortunately nothing I can do for you as OptiFine is closed source which means I can't check what they are doing that might break this.

I would suggest playing around with the settings to see if you can figure out where this is roughly coming from (mainly disabling or switching between shaders if you are using any and turning of Anti-Aliasing and similar features) and then reporting this to OptiFine to see if they have an idea what is breaking.
If they can provide evidence that the issue is in FramedBlocks as well as a solution to fix this, then I am more than happy to implement that. But until then, nothing I can do.
