### ISSUE TITLE
[1.18.1][Bug] Cannot disguise framed double doors

### ISSUE THREAD

**Issue by rafaelhr** [XFactHD/FramedBlocks#84]
* Issue: I'm using double framed doors, and I'm not able to use a block to disguise their appearances, as a right click only opens the doors. If I break one of them, I can disguise the other without a problem, but if I then place the second door it only opens and doesn't accept a block disguise as well. A screenshot of the issue:
![2022-02-20_16 58 59](https://user-images.githubusercontent.com/28713890/154861880-fa352a24-a8ac-4ae6-9626-f5357b2df4a0.png)

* Extra info: 
Minecraft 1.18.1
Forge 39.0.75
Framed Blocks 4.1.0

**Comment by XFactHD** [comment]
Your description sounds like you are using a mod that opens double doors simultaneously. I need to know which mod this feature comes from. In case you don't know, please force a debug crash (F3 + C for 10 seconds), put the crash report on https://gist.github.com and post the link here so I can identify the mod.

**Comment by rafaelhr** [comment]
You're right, I am using one of such mods (this one to be precise: [Link](https://www.curseforge.com/minecraft/mc-mods/double-doors)). I didn't even consider that possibility, but now solving my problem is trivial. Thanks!

**Comment by XFactHD** [comment]
I kinda suspected it would be that one specifically. Unfortunately there is nothing I can do about this due to how their implementation works (though I can't blame them for that, it's just how interaction events work).

As a workaround you have two options:

- If you want to put the same block on both halves of the door, then you can simply put that block in your off-hand and it will automatically be applied when you place the door with your main hand
- If you want different blocks on the two halves of the door, then you can place one door, apply the blocks, copy it with a Framed Blueprint, break it, place the second door, apply the blocks to that and then place the first door again from the blueprint. If both doors use the same combination of blocks, you can also just use the blueprint to copy the first door and place the second one with it without breaking the first one.
