### ISSUE TITLE
Crash after rotating block

### ISSUE THREAD

**Issue by LindaJuffermans** [XFactHD/FramedBlocks#97]
I placed a Framed Prism and rotated it with a crescent hammer. At some point it rotated to \\/ and it was invisible, I rotated it to /\ and it was still invisible. That's when Minecraft crashed.

[crash-2022-04-09_15.40.10-client.txt](https://github.com/XFactHD/FramedBlocks/files/8457039/crash-2022-04-09_15.40.10-client.txt)

(Modpack: Not Too Complicated 2; added FramedBlocks myself)

I wasn't able to load my world, tried to remove the item here but that didn't work:
![image](https://user-images.githubusercontent.com/31929183/162577054-91762b61-8806-44ee-9f52-ddab92d4b48b.png)

Had to restart my pack without FramedBlocks to fix my world.

**Comment by XFactHD** [comment]
The problem is that the Framed Prism has invalid combinations of state properties. The `facing` property denotes in which direction the base of the block points and the `axis` property denotes along which axis the top line of the triangle is oriented. This means that the `axis` must always be in parallel to the base of the block. The screenshot of your world data shows that this is not the case: `facing` is `UP` and `axis` is `Y`. Setting the `axis` property to `X` or `Z` would have fixed the crash.
The Crescent Hammer from Thermal doesn't know this though and due to the way they rotate other blocks, I have no way of preventing the rotation with the current layout of the data.

I will release an update with a simple fix that simply prevents this from crashing, the block will then just be a full cube and look like the block you originally used as the camo.

The proper fix would be to change the layout of the data but that would completely prevent you from rotating the block with wrenches from other mods and it would also break people's worlds, meaning this could only happen on the update to 1.19.

**Comment by LindaJuffermans** [comment]
I tried rotating with the Framed Wrench but it did nothing...

**Comment by XFactHD** [comment]
The Framed Wrench is intended for a different purpose, it's used to rotate the camo on the block (i.e. switch through the different orientations of an Oak Log applied to a Framed Block) and switching the latch type on the Framed Chest.

FramedBlocks by itself does not provide any facilities to rotate the blocks because the extensive placement behavior together with the placement preview should be enough to get the desired orientation in most cases.
